### ISSUE TITLE
Sync download not working in fresh install on new machine

### ISSUE THREAD

**Issue by Falconne** [shanalikhan/code-settings-sync#1007]
🐛 **Describe the bug**  
I have sync upload/download working fine on 3 machines already, but I just set up a new laptop with a fresh installation of VS Code with no extensions installed except for this one. Kicking off Sync Download fails with the error "Sync: Unable to remove some extensions." and the errors in the console pasted below.

🌴 **Visual Studio Code Version :** 1.37.1
🌴 **Code Settings Sync Version :** 3.4.1
🌴 **Standard or Insiders :** Standard
🌴 **Portable or Installed :** Installed
🌴 **OSS or Official Build :** Official
🌴 **Operating System :** Windows 10
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** fd71f0c9421fac0dd6bd4044197bcdff

📰 **To Reproduce**
1. Install Plugin
2. Connect to Github account and select gist
3. `Ctrl-Shift-P` -> `Sync: Download Settings`

💪 **Expected behavior**
Settings downloaded from gist

📺 **Console Error Log** 
```
console.ts:137 [Extension Host] Sync : Connected with user : 'Falconne'
notificationsAlerts.ts:40 Sync: Unable to remove some extensions.
onDidNotificationChange @ notificationsAlerts.ts:40
_register.model.onDidNotificationChange.e @ notificationsAlerts.ts:26
fire @ event.ts:572
addNotification @ notifications.ts:156
notify @ notificationService.ts:55
r @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:572
a @ ipc.net.ts:421
e @ ipc.net.ts:428
fire @ event.ts:572
_receiveMessage @ ipc.net.ts:715
S._socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:578
fire @ event.ts:572
acceptChunk @ ipc.net.ts:236
_register._socket.onData.e @ ipc.net.ts:197
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
console.ts:137 [Extension Host] Error: Error: TypeError: Cannot read property 'galleryApiUrl' of undefined	at c:\Users\***\.vscode\extensions\shan.code-settings-sync-3.4.1\out\extension.js:290:22030	at c:\Users\***\.vscode\extensions\shan.code-settings-sync-3.4.1\out\extension.js:290:11594	at Object.module.exports.i [as throw] (c:\Users\***\.vscode\extensions\shan.code-settings-sync-3.4.1\out\extension.js:290:11699)	at s (c:\Users\***\.vscode\extensions\shan.code-settings-sync-3.4.1\out\extension.js:290:10496)	at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Falconne** [comment]
I deleted all settings and started from fresh and it's all good now. I think I must have corrupted something before. Sorry about the incorrect report.
