### ISSUE TITLE
Sync: Error Logged In Console > HttpError: Validation Failed

### ISSUE THREAD

**Issue by hamed4000** [shanalikhan/code-settings-sync#1027]
at first time after login with github and says Success! when skip (new one will created ... ) Sync: Error Logged In Console (Help menu > Toggle Developer Tools).
![Annotation 2019-08-31 203801](https://user-images.githubusercontent.com/43178970/64066541-5d75ab80-cc30-11e9-8846-e53c1e2c1eca.jpg)

Visual Studio Code Version : 1.37.1
Code Settings Sync Version : 3.4.2
Operating System : Official Win 10 Pro
Proxy Enabled: No

**Comment by shanalikhan** [comment]
`v3.4.3` Released. Let me know if there is any problem :)

**Comment by Jerome1337** [comment]
@shanalikhan I still have the same error with the `v3.4.3`.

Here is the full error trace:

```
HttpError: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head>  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">  <meta http-equiv="X-UA-Compatible" content="IE=7" /><!-- css --><style type="text/css"> .dummyClassForJS{color:#fff}</style> <link rel="STYLESHEET" type="text/css" href="/mwg-internal/de5fs23hu73ds/files/default/css/iview.css" media="all"/><link rel="STYLESHEET" type="text/css" href="/mwg-internal/de5fs23hu73ds/files/default/css/styleguide.css" media="all"/><link rel="STYLESHEET" type="text/css" href="/mwg-internal/de5fs23hu73ds/files/default/css/widget.css" media="all"/><link rel="STYLESHEET" type="text/css" href="/mwg-internal/de5fs23hu73ds/files/default/css/print.css" media="print"/><!-- <link rel="STYLESHEET" type="text/css" href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css" /> -->  <script type="text/javascript" src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js"></script><script type="text/javascript" src="/mwg-internal/de5fs23hu73ds/files/default/scripts/global_scripts.js"></script><script type="text/javascript" src="/mwg-internal/de5fs23hu73ds/files/default/scripts/prototype.js"></script><script type="text/javascript" src="/mwg-internal/de5fs23hu73ds/files/default/scripts/widget.js"></script><script type="text/javascript" src="/mwg-internal/de5fs23hu73ds/files/default/scripts/tooltip.js"></script><script type="text/javascript" src="/mwg-internal/de5fs23hu73ds/files/default/scripts/theme.js"></script><title>Proxy Error Message </title></head> <!-- full body --><!-- Session and global vars for javascript are in this form --><body><!-- full body --><iframe id="helper_iframe" src="/mwg-internal/de5fs23hu73ds/files/default/images/loading_small.gif" class="helperIframe" style="display:none;"></iframe><!-- tooltip --><iframe id="tooltip_iframe" src="/mwg-internal/de5fs23hu73ds/files/default/images/loading_small.gif" class="helperIframe" style="display:none;"></iframe><div id="navtxt" class="navtext"><span id="tooltip_text"></span></div><div id="helptip" class="navtext"><span id="helptip_text"></span></div><!-- tooltip  END --> <div id="helper_div" class="helperDiv waitElement"></div><div id="waitElement_helper" style="z-index:99; position:absolute;"></div><div id="widgetContainer" style="z-index:100;position:absolute;"> </div> <div id="SiteIdentSet" class="siteIdentSet"></div><div id="SiteIdentContent" class="siteIdentContent"></div><div id="KeyVisSet" class="keyVisSet"></div><div id="KeyVisContent" class="keyVisContent"></div> <div id="LeftNavSet" class="leftNavSet"></div> <div id="SearchSet" class="searchSet"></div><div id="SearchContent" class="searchContent"></div><div id="HeaderSet" class="headerSet"><table border="0" cellspacing="0" cellpadding="0" style="width:100%;" summary=""><tr>    <td valign="bottom" class="headerLogo">        <a name="top"></a>    </td>    <td>        <!-- Space -->    </td>    <td class="textAlignRight" valign="middle">    </td></tr></table></div> <div id="ContentMainSet" class="contentMainSet"><table id="ContentMainSpacer" class="contentMainSpacer" border="0" cellspacing="0" cellpadding="0" summary=""><tr>    <td>&nbsp;</td></tr></table><div id="contentMainContent" class="contentMainContent"> <!-- get content dimensions begin --><table id="contentGetWidth" border="0" cellspacing="0" cellpadding="0" summary=""><tr><td> <table> <tr><td>    <table class="textAlignCenter">    <tr>        <td><div class="messageinformationIcon"> </div></td>        <td><!--Contents--><!-- FileName: authenticationrequired.html     Language: [en]--><!--Title--><table class='titleTable'>  <tr>    <td class='titleData'>      Authentication Required    </td>  </tr></table><!--/Title--><!--Content--><table class="contentTable">  <tr>    <td class="contentData">      You must be authenticated to access this URL.    </td>  </tr></table>    <script language="javascript" type="text/javascript">   urlprotocol = "https";   statuscode=407;   if(statuscode==401 && urlprotocol == "ftp"){      document.write("<form name=\"ftpform\" method=\"get\" action=\"\">");      document.write("<table class=\"contentData\">");      document.write("<tr><td class=\"contentData\" colspan=2>Please enter your credentials in the form below and click \"Access FTP\" button if your browser doesn't present authentication promt for FTP sites.</td></tr>");      document.write("<tr><td class=\"contentData\">Username:</td><td><input type=\"text\" id=\"ftpUsername\" name=\"ftpUsername\" size=40 /></td></tr>");      document.write("<tr><td class=\"contentData\">Password:</td><td><input type=\"password\" id=\"ftpPassword\" name=\"ftpPassword\" size=40 /></td></tr>");      document.write("<tr><td class=\"contentData\" colspan=2 align=center><input type=\"button\" onclick=\"redirectToFTP();\" value=\"Access FTP\" /></td></tr>");      document.write("</table>");      document.write("</form>");   }      function redirectToFTP(){      var username=unescape(document.getElementById("ftpUsername").value);      var password=unescape(document.getElementById("ftpPassword").value);      location.href = "ftp://"+username+":"+password+"@api.github.com:443"   }</script><!--/Content--><!--Info--><table class="infoTable">  <tr>    <td class="infoData">      <b>URL: </b>https://api.github.com<br />    </td>  </tr></table><!--/Info--><!--/Contents-->        </td>        <td> <div class="messageinformationIcon"> </div></td>    </tr>    </table></td></tr><tr></td></td></tr><tr><td></td></tr></table><p style=padding:4px;><font size="1" color="#707070">Client IP: 172.24.131.68 | Proxy:frcromwg8 | Time: Wed, 25 Sep 2019 13:24:59 GMT</font></p>    <!-- the main content ends here --><table id="tblFooter" cellspacing="0" cellpadding="0" summary="" class="tblFooter widthFull" style="width:100% !important"><tr>    <td id="footerline" class="textAlignRight footerline widthFull">    <table class="floatRight collapsedBorder" cellspacing="0" cellpadding="3" summary="">    <tr>        <td id="footerspace" class="widthAuto">&nbsp;&nbsp;</td>        <td class="">            <a href="javascript:window.print();" title="Print" style="text-decoration:none;">                <span class="buttonPrint" title="">&nbsp;</span>            </a>        </td>        <td>            <div title="Back to top" class="buttonBackToTop" onclick="self.location.href='#top';"></div>        </td>    </tr>    </table>    </td></tr><tr>    <td style="width: 100%; padding-top: 5px;">        <!--<hr id="footerline" noshade class="tblFooter" /> -->        <div class="footerMainText floatLeft">                    <a title="" class="footerMainText" target="_blank">&copy; Atos SE</a>&nbsp;                </div>    </td></tr><tr>    <td class="widthFull marginTopM marginLeftM footerMainText textAlignRight">         </td></tr></table> </td></tr></table><!-- get content dimensions end --></div></div>    <div id="FirstLevNavSet" class="firstLevNavSet"></div><div id="FirstLevNavContent" class="firstLevNavContent"></div><div id="CountryIdentSet" class="countryIdentSet"></div><div id="CountryIdentContent" class="countryIdentContent"> </div> <div id="GenNavSet" class="genNavSet"></div><div id="GenNavContent" class="genNavContent"></div><!-- country ident right--><div id="CountryIdentRightSet" class="countryIdentRightSet"></div><div id="CountryIdentRightContent" class="countryIdentRightContent"></div><div id="ContentRightSet" class="contentRightSet">    <div id="Style_ContentRightContent" class="contentRightContent"><table id="contentRightGetWidth" border="0" cellspacing="0" cellpadding="0" summary=""><tr>    <td>        </td> </tr></table></div></div><script type="text/javascript"> //<![CDATA[eventListener(); contentWidthData = '';layoutDirectionData = 'left';calculateStyleguide('','left'); Event.observe(window, 'resize', function(){calculateStyleguide('','left');}, false);Event.observe(window, 'onload', function(){setCursor('auto');}, false);Event.observe(window, 'onunload', function(){setCursor('wait');}, false);//]]></script></body></html>	at module.exports.then.t.text.then.t (c:\Users\a768649\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:761:736)	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ console.ts:137
```

Any recommendations?

**EDIT**

It's was a proxy problem

**Comment by ghost** [comment]
@Jerome1337 did you solve the proxy error somhow tho?

**Comment by Ashkan4472** [comment]
> `v3.4.3` Released. Let me know if there is any problem :)

still the error exists:
```
workbench.desktop.main.js:sourcemap:310 [Extension Host] Sync : Connected with user : 'Ashkan4472'
workbench.desktop.main.js:sourcemap:310 [Extension Host] HttpError: Validation Failed	at /home/ashkan/.vscode-oss/extensions/shan.code-settings-sync-3.4.3/out/extension.js:761:736	at processTicksAndRejections (internal/process/task_queues.js:94:5)
t.log @ workbench.desktop.main.js:sourcemap:310
$logExtensionHostMessage @ workbench.desktop.main.js:sourcemap:4510
_doInvokeHandler @ workbench.desktop.main.js:sourcemap:4517
_invokeHandler @ workbench.desktop.main.js:sourcemap:4516
_receiveRequest @ workbench.desktop.main.js:sourcemap:4515
_receiveOneMessage @ workbench.desktop.main.js:sourcemap:4514
(anonymous) @ workbench.desktop.main.js:sourcemap:4512
fire @ workbench.desktop.main.js:sourcemap:99
fire @ workbench.desktop.main.js:sourcemap:448
_receiveMessage @ workbench.desktop.main.js:sourcemap:453
(anonymous) @ workbench.desktop.main.js:sourcemap:450
fire @ workbench.desktop.main.js:sourcemap:99
acceptChunk @ workbench.desktop.main.js:sourcemap:445
(anonymous) @ workbench.desktop.main.js:sourcemap:445
t @ workbench.desktop.main.js:sourcemap:455
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
```
