### ISSUE TITLE
Error: Unable To Remove Some Extensions

### ISSUE THREAD

**Issue by kufii** [shanalikhan/code-settings-sync#1037]
When I try to download the settings for the first time another computer I get the following error

Error: Unable To Remove Some Extensions

```
Error: Error: TypeError: Cannot read property 'galleryApiUrl' of undefined	at c:\Users\adpyk\.vscode\extensions\shan.code-settings-sync-3.4.2\out\extension.js:290:21989	at c:\Users\adpyk\.vscode\extensions\shan.code-settings-sync-3.4.2\out\extension.js:290:11611	at Object.module.exports.i [as throw] (c:\Users\adpyk\.vscode\extensions\shan.code-settings-sync-3.4.2\out\extension.js:290:11716)	at s (c:\Users\adpyk\.vscode\extensions\shan.code-settings-sync-3.4.2\out\extension.js:290:10513)	at process._tickCallback (internal/process/next_tick.js:68:7)
```

🌴 **Visual Studio Code Version :** 1.38.0
🌴 **Code Settings Sync Version :** 3.4.2
🌴 **Standard or Insiders :** Standard
🌴 **Portable or Installed :** Itstalled
🌴 **OSS or Official Build :** Official
🌴 **Operating System :** Windows 10
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** 43fb5fbd24ac2922136b47c6d1f3ef7f

**Comment by kufii** [comment]
my issue was with the gist, I created a new one and it works
