### ISSUE TITLE
cannot authenticate

### ISSUE THREAD

**Issue by alicerocheman** [shanalikhan/code-settings-sync#1043]
🐛 **Describe the bug**  
I'm a first time user so my goal is to upload local settings to my github account.
I've installed the extension successfully but cannot get it to work. 
I've created a github token for the occasion, I've also created a gist so I could pass an id, but I cannot upload settings.

🌴 **Visual Studio Code Version :** 1.38.1
🌴 **Code Settings Sync Version :** 3.4.2
🌴 **Standard or Insiders :** [ _here_ ] 
🌴 **Portable or Installed :** [ _here_ ] 
🌴 **OSS or Official Build :** [ _here_ ] 
🌴 **Operating System :** Windows 10 Enterprise
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:** Yes
🌴 **Gist Id:** efe8b806eb42b4b36783a5060fc7af79 (empty gist with just a readme, created by hand on github)

📰 **To Reproduce**
I have no idea. I just installed and configured, once with login, once with token. Both failed. I tried with and without a gist id

💪 **Expected behavior**
Upload current local vscode config

📺 **Console Error Log** 
```
console.ts:137 [Extension Host] HttpError: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
<script type="text/javascript">document.location.href="http://fr0-proxy-vip.eu.airbus.corp/error/page.php?id=authentication_failed&proxy=fr0-proxylan-p01&summary=Access Denied&url=api.github.com&category=Technology/Internet;Office/Business Applications&user=&ip=44.10.126.11&details=Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified."</script>
<meta http-equiv="REFRESH" content="0;url='http://fr0-proxy-vip.eu.airbus.corp/error/page.php?id=authentication_failed&proxy=fr0-proxylan-p01&summary=Access Denied&url=api.github.com&category=Technology/Internet;Office/Business Applications&user=&ip=44.10.126.11&details=Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.'">
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Access Denied (authentication_failed)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact the Service Desk (8666).
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
	at module.exports.then.t.text.then.t (c:\Users\NG7B370\.vscode\extensions\shan.code-settings-sync-3.4.2\out\extension.js:761:736)	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:38
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:572
fire @ ipc.net.ts:449
_receiveMessage @ ipc.net.ts:729
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:588
fire @ event.ts:572
acceptChunk @ ipc.net.ts:235
_register._socket.onData.e @ ipc.net.ts:196
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
notificationsAlerts.ts:40 Sync: Erreur enregistré dans la Console (menu Aide > activer / désactiver les Outils de développement).
onDidNotificationChange @ notificationsAlerts.ts:40
_register.model.onDidNotificationChange.e @ notificationsAlerts.ts:26
fire @ event.ts:572
addNotification @ notifications.ts:156
notify @ notificationService.ts:101
r @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:572
fire @ ipc.net.ts:449
_receiveMessage @ ipc.net.ts:729
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:588
fire @ event.ts:572
acceptChunk @ ipc.net.ts:235
_register._socket.onData.e @ ipc.net.ts:196
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
```

📺  **Additional context**
syncLocalSettings.json:
````json
{
    "ignoreUploadFiles": [
        "state.*",
        "syncLocalSettings.json",
        ".DS_Store",
        "sync.lock",
        "projects.json",
        "projects_cache_vscode.json",
        "projects_cache_git.json",
        "projects_cache_svn.json",
        "gpm_projects.json",
        "gpm-recentItems.json"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "ignoreExtensions": [],
    "gistDescription": "Visual Studio Code Settings Sync Gist",
    "version": 342,
    "token": "", // removed token for security
    "downloadPublicGist": true,
    "supportedFileExtensions": [
        "json",
        "code-snippets"
    ],
    "openTokenLink": true,
    "disableUpdateMessage": false,
    "lastUpload": null,
    "lastDownload": null,
    "githubEnterpriseUrl": null,
    "askGistName": false,
    "customFiles": {},
    "hostName": null,
    "universalKeybindings": false,
    "autoUploadDelay": 20
}
````

**Comment by citrusjunoss** [comment]
I have some error like this: 

`The following error was encountered while trying to retrieve the URL: https://api.github.com/*

Cache Access Denied.

Sorry, you are not currently allowed to request https://api.github.com/* from this cache until you have authenticated yourself.

Please contact the cache administrator if you have difficulties authenticating yourself.

`

**Comment by citrusjunoss** [comment]
Seems to be a problem with the windows network。
vs code terminal also throw error 。
Then I tried to reinstall the system and everything was solved.

**Comment by shanalikhan** [comment]
> Proxy Enabled: Yes

@alicerocheman 
Can you try on latest `v3.4.3` version of Settings Sync. 
I think its the problem from your network itself like @citrusjunoss mentioned.
