### ISSUE TITLE
not able to do anything after login in to GitHub 

### ISSUE THREAD

**Issue by ghost** [shanalikhan/code-settings-sync#1051]
🐛 **Describe the bug** 
I tried installing it in both my laptop and desktop and I can't do anything after logging into GitHub. I have success logging in then when I try to do something it sends me to an outside link that leads to a page not found. and I also get an error that synclocalsettings.json is invalid. I checked several tutorials on how to install it but didn't see one with the same issue. tried to restart VScode, restart sync setting and reinstalling

🌴 **Visual Studio Code Version :** [ 1.38.1] 
🌴 **Code Settings Sync Version :** [ VERSION_HERE ] 
🌴 **Standard or Insiders :** [ _here_ ] 
🌴 **Portable or Installed :** [ _here_ ] 
🌴 **OSS or Official Build :** [ _here_ ] 
🌴 **Operating System :** [ windows 10 ] 
🌴 **Occurs On:** [ instaling ]
🌴 **Proxy Enabled:** [ Yes / No ]
🌴 **Gist Id:** [ ID_HERE ]

📰 **To Reproduce**
1. Installed the extension
2. logged in 
3. error 

💪 **Expected behavior**
The extension should create an automatic gist 

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode (Help Menu > Developer Tool - Console Tab). 

📺  **Additional context**

**Comment by zk-g** [comment]
Can you guys just re-upload the old version and for this new version create a new extension like "Settings Sync Alpha/Beta"?

I m not anymore able to upload settings and the old one was more comfortable.

Thanks

**Comment by shanalikhan** [comment]
U can always download the older versions of Settings Sync from vscode.
Also in releases tab there are older packages available.

What problem are you facing

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mazwak** [comment]
I'm having the same issue.
I use VSCode 1.38.1 and sync 3.4.3.

When I click « login with github », I get success.
In VSCode, I have the error « Sync : Unable to read syncLocalSettings.json. Make sure its valid JSON. »
And it tries to open an old entry from your blog you deleted : https://shanalikhan.github.io/2017/02/19/Option-to-ignore-settings-folders-code-settings-sync.html

I tried to reset config a few times, and it's always the same.

**Comment by Mazwak** [comment]
Forgot to say I'm using VSCodium fork, which does not use the same name for folders.
I don't think you use hard path though.

**Comment by shanalikhan** [comment]
>  I don't think you use hard path though.
Yes I'm not using hard path as of now.

What are you paths for `users` and extensions folder

>If applicable, add screenshots or paste the console log from developer console of VSCode (Help Menu > Developer Tool - Console Tab).

Can you post the image

**Comment by Mazwak** [comment]
the paths are :
C:\Users\<mylogin>\.vscode-oss
C:\Users\<mylogin>\AppData\Roaming\VSCodium

The only thing about sync in the console is :
```
Error: FetchError: invalid json response body at https://api.github.com/user reason: Unexpected token < in JSON at position 0
at e.<anonymous> (c:\Users\<mylogin>\.vscode-oss\extensions\shan.code-settings-sync-3.4.3\out\extension.js:560:74235)
at c:\Users\<mylogin>\.vscode-oss\extensions\shan.code-settings-sync-3.4.3\out\extension.js:560:71805
at Object.module.exports.i [as throw] (c:\Users\<mylogin>\.vscode-oss\extensions\shan.code-settings-sync-3.4.3\out\extension.js:560:71910)
at s (c:\Users\<mylogin>\.vscode-oss\extensions\shan.code-settings-sync-3.4.3\out\extension.js:560:70707)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

It might be my proxy doing bad thing.

**Comment by shanalikhan** [comment]
> It might be my proxy doing bad thing.

Exactly, you need to configure your network settings and vscode network settings to support proxy.

**Comment by Mazwak** [comment]
VSCode is configured. Auto-update and installing extensions works.

Is there a way to get the response in full ? Looks like it is HTML, as it fails on '<', but the whole response would be usefull.

**Comment by Mazwak** [comment]
The proxy was too paranoid. I had the IT departement fix it for another problem (https://github.com/seanmonstar/reqwest/issues/660) and it seems to be fixed now.

As a summary, the proxy was refusing connections if no User-Agent was set. I don't know if it your plugin in particular, or a vscode function you use which does not set it.

**Comment by Mazwak** [comment]
This afternoon, it seems the proxy is back to paranoid.
I don't know why, I get the whole response now, and I can confirm the connection is refused by the proxy with 407 auth required.
It is a non-auth proxy, which is configured to stop connections if no User-Agent is set.

From sniffing the HTTP connections, it seems to be the almost the same problem. I suspect it is because user-agent is all lowercase, instead of HTTP-Header-Case.

Here is a log :

> accept: application/vnd.github.v3+json
> user-agent: octokit.js/16.28.7 Node.js/10.11.0 (Windows 10; x64)
> authorization: token […]
> Accept-Encoding: gzip,deflate
> Host: api.github.com
> Connection: close

I really have no idea why some is lower case, and some http header case.

**Comment by Mazwak** [comment]
After further tests, I'm more and more puzled. I'm not sure it comes from case.

I won't test more until late next week, unless you have specifics to test.

**Comment by tycrek** [comment]
Also using VSCodium and am having the exact same problem. Logging in works fine, but then "Select Your Existing Gist" is just blank. No options to pick one or skip.

**Comment by shanalikhan** [comment]
@tycrek can you post your developer console log.

**Comment by rrlevy** [comment]
Same problem here.... Just installed it, logged into Github, and then when opening Configuratins page or trying to sync, it opens a 404 page.

Just tried in a different machine, a brand new Macbook Pro with MacOS Catalina, with a fresh VSCode install, and the exact same thing happens.

VSCode shows the error "Unable to read syncLocalSettings.json"

The file is correctly placed at the folder: 
/Users/<username>/Library/Application Support/Code/User/

VSCode version:

Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by rrlevy** [comment]
Console log. when entering the config page:

```
console.ts:137 [Extension Host] TypeError: Cannot read property 'trim' of null	at e.<anonymous> (/Users/<USERNAME>/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:74:8401)	at /Users/<USERNAME>/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:74:5423	at Object.next (/Users/<USERNAME>/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:74:5528)	at a (/Users/<USERNAME>/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:74:4274)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:581
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:581
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
notificationsAlerts.ts:40 Sync : Unable to read syncLocalSettings.json. Make sure its Valid JSON.
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:581
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:581
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:581
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
webviewElement.ts:241 [Embedded Page] jQuery.Deferred exception: Cannot read property 'forEach' of undefined
webviewElement.ts:241 [Embedded Page] Uncaught TypeError: Cannot read property 'forEach' of undefined
```

**Comment by rrlevy** [comment]
Also, when installing the extension for the first time, after logging in to Github, this error will show:

```
workbench.desktop.main.js:sourcemap:3553 Extension Host
workbench.desktop.main.js:sourcemap:3553 Sun, 15 Dec 2019 16:16:41 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at <anonymous>:null:null
workbench.desktop.main.js:sourcemap:254 [Extension Host] Error: TypeError: d.map is not a function    at e.<anonymous> (/Users/<USERNAME>/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:560:74235)    at /Users/<USERNAME>/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:560:71805    at Object.next (/Users/<USERNAME>/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:560:71910)    at a (/Users/<USERNAME>/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:560:70656)    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```
