### ISSUE TITLE
Error on upload on Linux OS (Pop OS)

### ISSUE THREAD

**Issue by artoodeeto** [shanalikhan/code-settings-sync#1055]
Hello there, first of all I want to say awesome tool. This really helps. So my issue is on my mac I uploaded my new settings (personal) and then at work I tried to download my new settings and It worked, but for some reason on my work pc I tried to upload/update my gist im getting an error on the console.

🌴 **Visual Studio Code Version :** 1.38.1 
 **Code Settings Sync Version :** 3.4.3
🌴 **Standard or Insiders :** Standard 
🌴 **Portable or Installed :** Installed 
🌴 **OSS or Official Build :** Official Build 
🌴 **Operating System :** Linux POP os V 18.10 
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:** no
🌴 **Gist Id:** **** 9ad3cad1ae598973eb4747991d1a3d0a

📰 **To Reproduce**
1. Upload new settings
2. Download it on a different computer (Linux os)
3. Upload new settings from Linux os
4. And a error will pop out. `Sync: Error Logged In Console (Help menu > Toggle Developer Tools).`

💪 **Expected behavior**
Upload a new settings from Linux os.

📺 **Console Error Log** 
```
console.ts:137 [Extension Host] Error: Invalid package /home/raphaelgako/.config/Code/User/globalStorage/ms-vsliveshare.vsliveshare-audio/electron-4.2.7/dist/Electron.app/Contents/Resources/default_app.asar    at createError (ELECTRON_ASAR.js:146:17)    at Object.exports.wrapFsWithAsar.fs.lstat (ELECTRON_ASAR.js:265:23)    at exports.wrapFsWithAsar.fs.stat.process.nextTick (ELECTRON_ASAR.js:300:33)    at process._tickCallback (internal/process/next_tick.js:61:11)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:38
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:572
fire @ ipc.net.ts:449
_receiveMessage @ ipc.net.ts:729
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:588
fire @ event.ts:572
acceptChunk @ ipc.net.ts:235
_register._socket.onData.e @ ipc.net.ts:196
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
notificationsAlerts.ts:40 Sync: Error Logged In Console (Help menu > Toggle Developer Tools).
```
```
[0930/074329.652470:ERROR:archive.cc(161)] Failed to read header size from /home/raphaelgako/.config/Code/User/globalStorage/ms-vsliveshare.vsliveshare-audio/electron-4.2.7/dist/Electron.app/Contents/Resources/default_app.asar: Is a directory (21)[0930/074329.653497:ERROR:archive.cc(161)] Failed to read header size from /home/raphaelgako/.config/Code/User/globalStorage/ms-vsliveshare.vsliveshare-audio/electron-4.2.7/temp/Electron.app/Contents/Resources/default_app.asar: Is a directory (21)
```
```
[Extension Host] No editors associated with document: /home/raphaelgako/.config/Code/User/syncLocalSettings.json
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:38
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:572
fire @ ipc.net.ts:449
_receiveMessage @ ipc.net.ts:729
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:588
fire @ event.ts:572
acceptChunk @ ipc.net.ts:235
_register._socket.onData.e @ ipc.net.ts:196
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
```

📺  **Additional context**
I don't know if this is an OS-specific error but I will add another detail when I get back home to try it on a different computer.

**Comment by fahrinh** [comment]
I got same issue on OSX but on different path (`/temp/`, not `/dist/`):
```
[1024/090803.669092:ERROR:archive.cc(161)] Failed to read header size from /Users/fahrihidayat/Library/Application Support/Code/User/globalStorage/ms-vsliveshare.vsliveshare-audio/electron-4.2.7/temp/Electron.app/Contents/Resources/default_app.asar: Is a directory (21)
```

This is my workaround:
```
rm -rf ~/Library/Application Support/Code/User/globalStorage/ms-vsliveshare.vsliveshare-audio/electron-4.2.7/temp
```

**Comment by artoodeeto** [comment]
@fahrinh wait so you deleted vscode liveshare? so the issue is not in the OS but other plugins? If so i think you should have uninstalled liveshare. ill try this one. thanks.

**Comment by shanalikhan** [comment]
>  Invalid package /home/raphaelgako/.config/Code/User/globalStorage/ms-vsliveshare.vsliveshare-audio/electron-4.2.7/dist/Electron.app/Contents/Resources/default_app.asar

I dont see any exception related to Settings Sync.

Try uninstalling that extension and restart code to start the process of download / upload
