### ISSUE TITLE
Sync: Unable to remove some extensions.

### ISSUE THREAD

**Issue by gost-serb** [shanalikhan/code-settings-sync#1140]
During reopening VSCode to another project with a different setting (different gist) Sync failed with 
error: `Sync: Unable to remove some extensions.`

```
Error: Error: Sync : Unable to delete extension vscode-eslint 2.0.15: Error:
Error: Extension 'dbaeumer.vscode-eslint' is not installed. Make sure you use the full extension
ID, including the publisher, e.g.: ms-vscode.csharp.
	at /home/gost/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:21729
        at /home/gost/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611	 
        at Object.throw (/home/gost/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11716)
	at s (/home/gost/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)
```

Occurrence: 3/10

Settings Sync Version: 3.4.3
VSCode version: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-76-generic (Virtual machine)

**Comment by gost-serb** [comment]
After closing VSCode and launching again works fine

**Comment by KaidiMohammed** [comment]
relaunch you vscode
