### ISSUE TITLE
"Extension Not Found" prevents download of other extensions

### ISSUE THREAD

**Issue by codymaust** [shanalikhan/code-settings-sync#1144]
🐛 **Describe the bug**  
During sync, if one of the extensions is no longer available, the remaining extensions are not synced. 

While syncing `extensions.json` - 
1. Sync Extension A (SUCCESS)
2. Sync Extension B (FAILS - extension not found)
3. Extention C is not synced
4. Extension D is not synced

In the gist, `joshpeng.sublime-babel-vscode` is the offending extension. Removing that extension allows the download to work as expected

🌴 **Visual Studio Code Version :** 1.42.1
🌴 **Code Settings Sync Version :** 3.4.3 
🌴 **Standard or Insiders :** Standard 
🌴 **Portable or Installed :** Installed 
🌴 **OSS or Official Build :** Official
🌴 **Operating System :** Linux - Debian 10 
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** daafa9b496b8bf332beab39196a7fd17

📰 **To Reproduce**
1. Start with a fresh install
2. Install Sync extension
3. Configure Sync extension
4. Download Settings
5. Error will occur, you'll need to open developer tools to see the details

💪 **Expected behavior**
The missing/invalid extension is skipped, and the rest of the `extensions.json` file is processed
Optionally it would be good to notify the user exactly which extension is invalid, without requiring them to open the Dev Tools

📺 **Console Error Log** 
```
[Extension Host] Error: Error: Error: Extension 'joshpeng.sublime-babel-vscode' not found.
    at /home/cody/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:22293
    at /home/cody/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611
    at Object.throw (/home/cody/.vscode/extensions/shan.code-settings-sync-3.4.3 out/extension.js:290:11716)
    at s (/home/cody/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)
```

📺  **Additional context**
Issue occurred on a fresh install of VSCode

**Comment by codymaust** [comment]
i'm going to look into the code and see if i can put together a PR for this issue myself, but wanted to submit it first

**Comment by MrLonelee** [comment]
You can set the missing/invalid extension to "ignore extensions"

**Comment by BtM909** [comment]
There could be an option in the settings as well, allowing you to break on failure or continue onwards. Besides that, an error (hard or soft) should be in the output window.

@codymaust, if you need help / assistance, let me know.

**Comment by arthedza** [comment]
You can also delete the missing extension from the gist manually.

**Comment by BtM909** [comment]
> You can also delete the missing extension from the gist manually.

Correct, but then again: that's the known workaround.

**Comment by odravison** [comment]
> You can also delete the missing extension from the gist manually.

How to do that? I'm facing the same problem!

**Comment by arthedza** [comment]
> > You can also delete the missing extension from the gist manually.
> 
> How to do that? I'm facing the same problem!

Just go to your gists on GitHub, then find the Visual Studio Code Settings Sync Gist which name can be 'cloudSettings' one (I don't remember details). And all you need is to edit the file 'extensions.json'.

**Comment by odravison** [comment]
> > > You can also delete the missing extension from the gist manually.
> > 
> > 
> > How to do that? I'm facing the same problem!
> 
> Just go to your gists on GitHub, then find the Visual Studio Code Settings Sync Gist which name can be 'cloudSettings' one (I don't remember details). And all you need is to edit the file 'extensions.json'.

Thank you, bro!
