### ISSUE TITLE
Installation issue on mac

### ISSUE THREAD

**Issue by marcandre** [shanalikhan/code-settings-sync#1155]
🐛 **Describe the bug**  
Just installed the extension.
Login with Github button opens a tab but hangs

Console shows error:
```
HttpError: request to https://api.github.com/gists failed, reason: certificate has expired	at /Users/mal/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:761:1113	at processTicksAndRejections (internal/process/task_queues.js:89:5)
t.log @ console.ts:137

log.ts:197   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

Tried manual settings, then "Upload / update settings" gives me similar errors:
```
console.ts:137 [Extension Host] HttpError: request to https://api.github.com/user failed, reason: certificate has expired	at /Users/mal/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:761:1113	at processTicksAndRejections (internal/process/task_queues.js:89:5)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:582
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:582
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] HttpError: request to https://api.github.com/gists/37f9b0f75d95e3f9a74e0aaba8515785 failed, reason: certificate has expired	at /Users/mal/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:761:1113	at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

🌴 **Visual Studio Code Version :**1.42.1
🌴 **Code Settings Sync Version :**3.4.3
🌴 **Standard or Insiders :** Standard?
🌴 **Portable or Installed :** Installed?
🌴 **OSS or Official Build :** Official 
🌴 **Operating System :** Mac OS 10.14.6
🌴 **Occurs On:** Upload & Help Configuring 
🌴 **Proxy Enabled:** No?
🌴 **Gist Id:** 37f9b0f75d95e3f9a74e0aaba8515785 (private)

**Comment by samgutentag** [comment]
bump this, getting the same error and forcing an update/upload seems to be creating a new gist every time
