### ISSUE TITLE
Getting sync error for an extension that I don't have.

### ISSUE THREAD

**Issue by ericklind** [shanalikhan/code-settings-sync#1168]
🐛 **Describe the bug**  
I'm trying to sync from my work computer. I have cleared out all extensions on my home system so it should be a clean slate. The error I keep getting is:

`Unable to delete extension node-debug2 1.42.1: Error: Error: Cannot uninstall extension 'Node Debug'. Extension 'React Native Tools' depends on this.
`
The thing is, I don't have React Native Tools installed anywhere so I don't know why I'm getting this error.

🌴 **Visual Studio Code Version :** [1.43.0] 
🌴 **Code Settings Sync Version :** [3.4.3] 
🌴 **Standard or Insiders :** [Standard] 
🌴 **Portable or Installed :** [ Installable ] 
🌴 **OSS or Official Build :** [ Official ] 
🌴 **Operating System :** [ MacOs Catalina ] 
🌴 **Occurs On:** [Download ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ b850a9ebbbe24346b066f4c6621dbfbd ]

📰 **To Reproduce**
1. Go to Prompt
2. Select Sync: Download
3. See errors: 
- Sync: Unable to remove some extensions.
- Sync: Error Logged In Console (Help menu > Toggle Developer Tools).

💪 **Expected behavior**
Download extensions

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode (Help Menu 
`Sync: Error Logged In Console (Help menu > Toggle Developer Tools).
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:183
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] Sync : Connected with user : 'ericklind'
log.ts:197   ERR Cannot uninstall extension 'Node Debug'. Extension 'React Native Tools' depends on this.: Error: Cannot uninstall extension 'Node Debug'. Extension 'React Native Tools' depends on this.
    at j.uninstallExtensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:479:512)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:479:189
notificationsAlerts.ts:40 Sync: Unable to remove some extensions.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:183
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] Error: Error: Sync : Unable to delete extension node-debug2 1.42.1: Error: Error: Cannot uninstall extension 'Node Debug'. Extension 'React Native Tools' depends on this.	at /Users/erick/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:21729	at /Users/erick/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611	at Object.throw (/Users/erick/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11716)	at s (/Users/erick/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
notificationsAlerts.ts:40 Sync: Error Logged In Console (Help menu > Toggle Developer `

📺  **Additional context**

**Comment by ericklind** [comment]
I did some more digging, and somehow there was an extension folder for React-native left there. I deleted it and was able to sync.
