### ISSUE TITLE
I cannot download my settings because of a missing extension

### ISSUE THREAD

**Issue by odravison** [shanalikhan/code-settings-sync#1175]
There is 27 extensions associated to my Gist Token. Only 9 extensions could be installed because of a missing extension.

Follow the console log in Visual Code Studio:

```
workbench.desktop.main.js:sourcemap:258 [Extension Host] Sync : Connected with user : 'odravison'
workbench.desktop.main.js:sourcemap:1647   ERR Extension 'joshpeng.sublime-babel-vscode' not found.: Error: Extension 'joshpeng.sublime-babel-vscode' not found.
    at handler (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6399:934)
workbench.desktop.main.js:sourcemap:258 [Extension Host] Error: Error: Error: Extension 'joshpeng.sublime-babel-vscode' not found.	at /home/odravison/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:22293	at /home/odravison/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611	at Object.throw (/home/odravison/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11716)	at s (/home/odravison/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)
t.log @ workbench.desktop.main.js:sourcemap:258
$logExtensionHostMessage @ workbench.desktop.main.js:sourcemap:3674
_doInvokeHandler @ workbench.desktop.main.js:sourcemap:3681
_invokeHandler @ workbench.desktop.main.js:sourcemap:3681
_receiveRequest @ workbench.desktop.main.js:sourcemap:3679
_receiveOneMessage @ workbench.desktop.main.js:sourcemap:3678
(anonymous) @ workbench.desktop.main.js:sourcemap:3676
fire @ workbench.desktop.main.js:sourcemap:110
fire @ workbench.desktop.main.js:sourcemap:382
_receiveMessage @ workbench.desktop.main.js:sourcemap:387
(anonymous) @ workbench.desktop.main.js:sourcemap:384
fire @ workbench.desktop.main.js:sourcemap:110
acceptChunk @ workbench.desktop.main.js:sourcemap:380
(anonymous) @ workbench.desktop.main.js:sourcemap:379
t @ workbench.desktop.main.js:sourcemap:390
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
workbench.desktop.main.js:sourcemap:2786 Sync: Error Logged In Console (Help menu > Toggle Developer Tools).
```

Also I take a print to a more readable console log:

![Screenshot from 2020-03-26 23-49-37](https://user-images.githubusercontent.com/7316524/77716296-973b4480-6fbc-11ea-98a6-01aac64246c8.png)

How to resolve this issue? 
If someone help me, I'll appreciate it.

**Comment by odravison** [comment]
I figured out how to resolve this situation.

1. Open your visual code and press CTRL+SHIT+P or the equivalent for your machine (if mac)
2. You must access Sync: Advanced Option > Open Settings;
3. Inside of Open Settings, click on label "Ignored Extension";
4. A text-area must be opened then you must paste the name of the trouble extension on it;

That's it, you can download again without (or not) trouble again.

**Comment by leanne1** [comment]
Thank you! Helped me a lot!
