### ISSUE TITLE
Empty value for parameter 'id': null

### ISSUE THREAD

**Issue by davidsk** [shanalikhan/code-settings-sync#119]
**Visual Studio Code Version :** 1.6.1
**Code Sync Settings Version :** 2.3.3
**Operating System :** Windows 10 Version 1511 Build 10586.633
**Occurs On:** Add Git Credentials

TypeError: Cannot read property 'id' of undefined
    at C:\Users\keith\.vscode\extensions\Shan.code-settings-sync-2.3.3\out\src\githubService.js:72:24
    at global.sendError (C:\Users\keith\.vscode\extensions\Shan.code-settings-sync-2.3.3\node_modules\github\lib\index.js:785:13)
    at C:\Users\keith\.vscode\extensions\Shan.code-settings-sync-2.3.3\node_modules\github\lib\index.js:792:29
    at callCallback (C:\Users\keith\.vscode\extensions\Shan.code-settings-sync-2.3.3\node_modules\github\lib\index.js:667:17)
    at IncomingMessage.<anonymous> (C:\Users\keith\.vscode\extensions\Shan.code-settings-sync-2.3.3\node_modules\github\lib\index.js:723:25)

I'm installing the extension on my second machine and needed to reset the my github key if that's of any relevence

Thanks,

Keith

**Comment by shanalikhan** [comment]
Try with command "Sync : Reset Settings" and than add the settings again.
U need to insert that gist KEY that was generated by the extension from the first computer.
