### ISSUE TITLE
Extension 'maddouri.cmake-tools-helper' not found , it will stop sync 

### ISSUE THREAD

**Issue by tongxian** [shanalikhan/code-settings-sync#1192]
`/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Error: Error: Error: Extension 'maddouri.cmake-tools-helper' not found.	at /Users/sean/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:22293	at /Users/sean/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611	at Object.throw (/Users/sean/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11716)	at s (/Users/sean/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)`

I think it should skip the extensions if can't find it .

**Comment by Neutrino-Sunset** [comment]
You can configure the extension to skip selected extensions for a particular local installation.

In VsCode ctrl+shift+p run Sync: Advanced Options, select Sync: Edit Extension Local Settings.

Disable sync for specific extensions using ignoreExtensions. E.g.

```
    "ignoreExtensions": [
        "NativeScript"
    ],
```
