### ISSUE TITLE
Problem downloading

### ISSUE THREAD

**Issue by volkerdobler** [shanalikhan/code-settings-sync#1200]
Hello,

when I try to download my settings from a gist, I got the following error message in the console:

Error: Error: Error: Extension 'Denis-net.vscode-ahk-manager' not found.
    at c:\Users\volker\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:22293
    at c:\Users\volker\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11611
    at Object.throw (c:\Users\volker\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11716)
    at s (c:\Users\volker\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:10513)
/C:/Users/volker/App…esktop.main.js:2855 Sync: Fehler wurde in der Konsole protokolliert. Um die Konsole zu öffnen gehen Sie wie folgt vor (Menü Hilfe > Entwicklungstools umschalten).

The extension "Denis-net.vscode-ahk-manager" is no longer available. Maybe this throw the error?

Best regards,
Volker

**Comment by volkerdobler** [comment]
P.S. after a new "upload" it works without error - but maybe in a future version, the missing extensions should not bring an error and just silently ignore or delete this item? (so it's more a "feature" request? :-)

Thanks,
Volker

**Comment by anionDev** [comment]
i have the same problem (with the extension https://marketplace.visualstudio.com/items?itemName=bitlang.cobol-plus-pack ). i would treat it as bug because i am now unable to download my settings until i have uploaded settings without this deleted plugin. but i must upload the settings from the place[computer] where i have my uploaded my current settings last time because otherwise i would probably overwrite the new settings in my github-gist with old settings. this is not very nice. Code-Settings-Sync is a very nice plugin and it would be great if this issue could be fixed in future.
