### ISSUE TITLE
Can't login via github : Invalid GitHub Enterprise URL.

### ISSUE THREAD

**Issue by xiangnanscu** [shanalikhan/code-settings-sync#1220]
🐛 **Describe the bug**  
windows 10 2004, I install it and try logining with github and this error:

🌴 **Visual Studio Code Version** :1.46.1(system setup)
🌴 **Code Settings Sync Version** :3.4.3
🌴 **Standard or Insiders** :standard
🌴 **Portable or Installed** :installed
🌴 **OSS or Official Build** :official
🌴 **Operating System** : windows 10 2004
🌴 **Occurs On**: login
🌴 **Proxy Enabled**: no
🌴 **Gist Id**:

📰 **To Reproduce**
just press login with github

📺 **Console Error Log** 
```
FetchError: request to https://api.github.com/user failed, reason: read ECONNRESET	at ClientRequest.<anonymous> (c:\Users\xiang\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:151:24956)	
at ClientRequest.emit (events.js:208:15)	at TLSSocket.socketErrorListener (_http_client.js:399:9)	
at TLSSocket.emit (events.js:203:13)	
at emitErrorNT (internal/streams/destroy.js:91:8)	
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)	
at processTicksAndRejections (internal/process/task_queues.js:77:11)
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:265

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2932 Sync: Invalid GitHub Enterprise URL.
onDidChangeNotification @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2932

```

📺  **Additional context**

**Comment by xiangnanscu** [comment]
I think I've found the reason. I use vscode system version in a non-administrator account. If I switch to vscode user version, this problem gone

**Comment by xiangnanscu** [comment]
It seems to be vscode system version bug because even if I use administrator account the bug is still there

**Comment by Katherraptor** [comment]
Seeing this on my machine as well with a clean install of vscode as the single admin user on my computer.

**Comment by qrqhuang** [comment]
As mentioned above,  I open vscode with `run as administrator`, then it works.
But I still don't know why
