### ISSUE TITLE
Download settings crash if remote extension is not found

### ISSUE THREAD

**Issue by distante** [shanalikhan/code-settings-sync#1227]
🐛 **Describe the bug**  
If the remote settings contains an extension that does not exist anymore, instead of skipping it, show a warning and continue with the others the extension crash:

🌴 **Visual Studio Code Version :** 1.47 
🌴 **Code Settings Sync Version :** 3.4.3
🌴 **Standard or Insiders :** Standard
🌴 **Portable or Installed :** Installed 
🌴 **OSS or Official Build :** Official
🌴 **Operating System :** Windows
🌴 **Occurs On:** Download

📰 **To Reproduce**
1. Download Settings
2. See error

💪 **Expected behavior**
The extension should show a warning but keep downloading and installed the other available extensions

📺 **Console Error Log** 
```
Error: Error: Error: Extension 'HvyIndustries.crane' not found.    at c:\Users\dista\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:22293    at c:\Users\dista\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11611    at Object.throw (c:\Users\dista\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11716)    at s (c:\Users\dista\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:10513)    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by wsyqn6** [comment]
📺 Console Error Log
 Error: Error: Error: Extension 'ms-vscode.Go' not found.

**Comment by pushbuttons** [comment]
Yepppp ^^^

🌴 Visual Studio Code Version : 1.47.1
🌴 Code Settings Sync Version : 3.4.3
🌴 Operating System : OSX 10.5.5

❗ **ERROR**
Sync: Error Logged In Console
"[Extension Host] Error: Error: Error: Extension 'ms-vscode.csharp' not found"


💪 **Expected behaviour:**
The extension should show a warning but keep downloading and installed the other available extensions

**Comment by nandgator** [comment]
Yep same here. Any quick workaround?
```js
Error: Error: Error: Extension 'ms-vscode.cmake-tools' not found.
    at /home/joe733/.vscode-oss/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:22293
    at /home/joe733/.vscode-oss/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611
    at Object.throw (/home/joe733/.vscode-oss/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11716)
    at s (/home/joe733/.vscode-oss/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by n4nn31355** [comment]
> Any quick workaround?

Edit gist manually? =)

**Comment by d0ruk** [comment]
I started editing the gist manually, and deleting every extension it can't locate. Then it got to a vital extension, and I stopped butchering my settings.

If you are using Code OSS, extension servers appear to be a mirror of the official vscode repo. Some extensions are not mirrored there, and it cannot access the official repo.

Download and use one of the MS branded versions (i.e. insiders) to get your extensions back.

Well played, MS, well played..

edit: Using official git binary but now it's stuck on an *official* extension: ms-vscode-remote/remote-containers. It might be because I am running this setup on a VM. Nevertheless, this extension is broken.

edit2: The error message I get for that official ext is; *Error: Error: validating: Corrupt ZIP: end of central directory record signature not found* at /home/user/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:22293

**Comment by toremato** [comment]
So no workaround so far? I guess in my case the problem is that I installed most extensions while working on Windows. And now, when trying to download extensions on ubuntu it gets stuck with this error

**Comment by toremato** [comment]
okay, it seems this extension is no longer supported, so I'm just going to move to VSCode's offical settings syncronizer (still in preview) 

RIP Settings Sync

**Comment by nandgator** [comment]
Not yet, I'm don't think so. Last commit was a few months back https://github.com/shanalikhan/code-settings-sync/tree/v3.4.4, maybe the developer is busy with something else. Instead of official sync, for the time being I use: https://github.com/nonoroazoro/vscode-syncing/

**Comment by snowman** [comment]
Quick fix:
```sh
# download settings
$ git clone https://gist.github.com/USER_NAME/GIST_ID
$ cd GIST_ID
# remove some extensions not found by editing extensions.json
$ emacs extensions.json
# upload changes
$ git push
# now sync your settings in vscode

# after sync settings, revert the gist changes
$ git reset --hard HEAD~
$ git push --force
```
