### ISSUE TITLE
BUG: Sync installation crashed

### ISSUE THREAD

**Issue by theMajc** [shanalikhan/code-settings-sync#1232]
Extension halts/crashes when installing `vscode-leetcode`. Can be reproduced and after restarting VS Code.

`Sync: Error Logged In Console (Help menu > Toggle Developer Tools).`

```
Realtime Extension Download Summary
--------------------
TOTAL EXTENSIONS : 6



[x] - EXTENSION: vscode-leetcode - INSTALLING
```

VS console log:
```
Extension Host
console.ts:137 [Extension Host] Error: Error: Error: Extension 'shengchen.vscode-leetcode' not found.
	at c:\Users\majc\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:22293
	at c:\Users\majc\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11611
	at Object.throw (c:\Users\majc\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11716)
	at s (c:\Users\majc\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:10513)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
t.log	@	console.ts:137
notificationsAlerts.ts:40 Sync: Error Logged In Console (Help menu > Toggle Developer Tools).
onDidChangeNotification	@	notificationsAlerts.ts:40
2
console.ts:137 [Extension Host] (node:10708) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log	@	console.ts:137
2
console.ts:137 [Extension Host] (node:10708) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
	at u.<anonymous> (c:\Users\majc\.vscode\extensions\softwaredotcom.swdc-vscode-2.2.32\dist\extension.js:3:85879)
	at Generator.next (<anonymous>)
	at o (c:\Users\majc\.vscode\extensions\softwaredotcom.swdc-vscode-2.2.32\dist\extension.js:3:83584)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
t.log	@	console.ts:137
2
console.ts:137 [Extension Host] (node:10708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
t.log	@	console.ts:137
```

**Comment by theMajc** [comment]
Actually. Found out this is a duplicate of https://github.com/shanalikhan/code-settings-sync/issues/1227
