### ISSUE TITLE
Error: Error: Error: Extension 'HvyIndustries.crane' not found

### ISSUE THREAD

**Issue by LogicalAnt** [shanalikhan/code-settings-sync#1245]
🐛 **Describe the bug**  
A clear and concise description of what the bug is. You are always welcome to check the [Troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) section before filing the ticket.

🌴 **Visual Studio Code Version :** [ 1.48.0 ] 
🌴 **Code Settings Sync Version :** [ v3.4.3 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ Official Build ] 
🌴 **Operating System :** [ Linux Mint 20 Cinnamon ] 
🌴 **Occurs On:** [ Download ]
🌴 **Proxy Enabled:** [  No ]
🌴 **Gist Id:** [ c02c5927ec3a41ff920f144f4b5050ab ]

📰 **To Reproduce**
1. Uploaded my settings from a Mac machine
2. Downloaded that settings from a Linux machine
3. While downloading settings to Linux machine shows error

💪 **Expected behavior**
Should hop into the next package download instead of freezing the sync

📺 **Console Error Log** 
`Error: Error: Error: Extension 'HvyIndustries.crane' not found.    at /home/xxx/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:22293    at /home/xxx/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611    at Object.throw (/home/xxx/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11716)    at s (/home/xxx/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)    at processTicksAndRejections (internal/process/task_queues.js:85:5)`
📺  **Additional context**

**Comment by wwarriner** [comment]
Thanks for the wonderful package, it's been incredibly useful!

I've noticed the issue reported by the OP occurs for third-party VSCode servers, where the official marketplace is off-limits. If the third-party marketplace isn't a complete mirror of the official marketplace the extension just gives up, rather than moving to try the next package. This demolishes the utility of this package for syncing local settings with cluster settings in a VSCode server context. Is it possible to change the error to a warning, and continuing? Either by default or as an option.

**Comment by mrpaulphan** [comment]
Also having this issue :(
