### ISSUE TITLE
sync:Error Logged in Console 

### ISSUE THREAD

**Issue by tazik561** [shanalikhan/code-settings-sync#1263]
I installed setting sync and after login with github, and  after clicking on 
SKIP (NEW ONE WILL  BE CREATE UPON FIRST UPLOAD)
i got this error:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/bJFFR.png

this is my vs info:
```
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:56:11.027Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.19.0-6-amd64
```

I think this is it's error:

```
workbench.desktop.main.js:sourcemap:287 [Extension Host] HttpError: Validation Failed	at /home/tazik/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:761:736	at processTicksAndRejections (internal/process/task_queues.js:94:5)
t.log @ workbench.desktop.main.js:sourcemap:287
```

**Comment by wassimbj** [comment]
same

**Comment by MiloudiMohamed** [comment]
Same error

**Comment by yubaoquan** [comment]
Same on windows 10
```
Error: Error: Canceled: Canceled    
at c:\Users\111\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:22293    
at c:\Users\111\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11611    
at Object.throw (c:\Users\111\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11716)    
at s (c:\Users\111\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:10513)    
at processTicksAndRejections (internal/process/task_queues.js:97:5)

Sync: Error Logged In Console (Help menu > Toggle Developer Tools).
```

**Comment by zh-pan** [comment]
me too

**Comment by zh-pan** [comment]
> me too

ok,I solved this problem.Because I found that I uploaded an empty configuration by mistake on the new host, resulting in the new gist content being empty. I just deleted it on github, make sure your gist ID is the configuration you want.

**Comment by wwarriner** [comment]
It looks like it fails whenever it can't find an extension on the marketplace. Happened to me with `ms-python.anaconda-extension-pack`, which apparently no longer exists. Seems like swallowing the error (or converting to a warning?) would work out ok?

**Comment by imnickvaughn** [comment]
HOw am I supposed to know which extension it is having trouble finding?
