### ISSUE TITLE
The download script stop when an extension not exists

### ISSUE THREAD

**Issue by papac** [shanalikhan/code-settings-sync#1319]
workbench.desktop.main.js:sourcemap:71 [Extension Host] Error: Error: Error: Extension 'felixfbecker.php-intellisense' introuvable.    at /Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:22293    at /Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611    at Object.throw (/Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11716)    at s (/Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)    at processTicksAndRejections (internal/process/task_queues.js:93:5)
v @ workbench.desktop.main.js:sourcemap:71
$logExtensionHostMessage @ workbench.desktop.main.js:sourcemap:1523
_doInvokeHandler @ workbench.desktop.main.js:sourcemap:1523
_invokeHandler @ workbench.desktop.main.js:sourcemap:1523
_receiveRequest @ workbench.desktop.main.js:sourcemap:1523
_receiveOneMessage @ workbench.desktop.main.js:sourcemap:1523
(anonymous) @ workbench.desktop.main.js:sourcemap:1523
fire @ workbench.desktop.main.js:sourcemap:69
fire @ workbench.desktop.main.js:sourcemap:85
_receiveMessage @ workbench.desktop.main.js:sourcemap:85
(anonymous) @ workbench.desktop.main.js:sourcemap:85
fire @ workbench.desktop.main.js:sourcemap:69
acceptChunk @ workbench.desktop.main.js:sourcemap:85
(anonymous) @ workbench.desktop.main.js:sourcemap:85
_ @ workbench.desktop.main.js:sourcemap:2942
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:sourcemap:786 Sync: Erreur enregistré dans la Console (menu Aide > activer / désactiver les Outils de développement).
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:786
(anonymous) @ workbench.desktop.main.js:sourcemap:786
fire @ workbench.desktop.main.js:sourcemap:69
addNotification @ workbench.desktop.main.js:sourcemap:788
notify @ workbench.desktop.main.js:sourcemap:1576
(anonymous) @ workbench.desktop.main.js:sourcemap:1516
_showMessage @ workbench.desktop.main.js:sourcemap:1516
$showMessage @ workbench.desktop.main.js:sourcemap:1516
_doInvokeHandler @ workbench.desktop.main.js:sourcemap:1523
_invokeHandler @ workbench.desktop.main.js:sourcemap:1523
_receiveRequest @ workbench.desktop.main.js:sourcemap:1523
_receiveOneMessage @ workbench.desktop.main.js:sourcemap:1523
(anonymous) @ workbench.desktop.main.js:sourcemap:1523
fire @ workbench.desktop.main.js:sourcemap:69
fire @ workbench.desktop.main.js:sourcemap:85
_receiveMessage @ workbench.desktop.main.js:sourcemap:85
(anonymous) @ workbench.desktop.main.js:sourcemap:85
fire @ workbench.desktop.main.js:sourcemap:69
acceptChunk @ workbench.desktop.main.js:sourcemap:85
(anonymous) @ workbench.desktop.main.js:sourcemap:85
_ @ workbench.desktop.main.js:sourcemap:2942
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:sourcemap:71 [Extension Host] Sync : Connected with user : 'papac'
workbench.desktop.main.js:sourcemap:603   ERR Extension 'felixfbecker.php-intellisense' introuvable.: Error: Extension 'felixfbecker.php-intellisense' introuvable.
    at handler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2936:31244)
workbench.desktop.main.js:sourcemap:603   ERR [Extension Host] Error: Error: Error: Extension 'felixfbecker.php-intellisense' introuvable.
    at /Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:22293
    at /Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611
    at Object.throw (/Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11716)
    at s (/Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
workbench.desktop.main.js:sourcemap:71 [Extension Host] Error: Error: Error: Extension 'felixfbecker.php-intellisense' introuvable.    at /Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:22293    at /Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611    at Object.throw (/Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11716)    at s (/Users/mac/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by H0nGzA1** [comment]
i also meet this issue,did you work out it?

**Comment by MaximilianGaedig** [comment]
I think it would be nice if you could set a "ignore errors" flag as I also encounter these problems when having different versions of vscode, code-oos, vscodium

**Comment by jonas-w** [comment]
Agreed, there should be something that skips the extension when not found instead of stopping the sync process

**Comment by GJKrupa** [comment]
I'm seeing this now that the Bracket Pair Colorizer extension has been deprecated. Even if I force install and uninstall the extension on one machine then upload the settings, it still uploads the extension in the sync and tries to install it when I download settings on another machine.

**Comment by caiqalmeida** [comment]
Im having the same problem, i tried to edit the gist, but no success
