### ISSUE TITLE
Can't sync my settings.

### ISSUE THREAD

**Issue by blopez2010** [shanalikhan/code-settings-sync#132]
**Visual Studio Code Version :**  1.7.1 (1.7.1)
**Code Sync Settings Version :** 2.3.6
**Operating System :** 10.12.1 MacOS Sierra
**Occurs On:** Upload
**Proxy Enabled:** Both (Connect and disconnected to VPN)

[Extension Host] Darwin
extensionHost.ts:255[Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}I.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:255[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'id' of undefinedI.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:255[Extension Host] TypeError: Cannot read property 'id' of undefined
    at /Users/blopez/.vscode/extensions/Shan.code-settings-sync-2.3.6/out/src/githubService.js:75:24
    at global.sendError (/Users/blopez/.vscode/extensions/Shan.code-settings-sync-2.3.6/node_modules/github/lib/index.js:785:13)
    at /Users/blopez/.vscode/extensions/Shan.code-settings-sync-2.3.6/node_modules/github/lib/index.js:792:29
    at callCallback (/Users/blopez/.vscode/extensions/Shan.code-settings-sync-2.3.6/node_modules/github/lib/index.js:667:17)
    at IncomingMessage.<anonymous> (/Users/blopez/.vscode/extensions/Shan.code-settings-sync-2.3.6/node_modules/github/lib/index.js:723:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)I.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:255[Extension Host] Empty value for parameter 'id': nullI.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
shell.ts:440Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at /Users/blopez/.vscode/extensions/Shan.code-settings-sync-2.3.6/out/src/githubService.js:75:24
    at global.sendError (/Users/blopez/.vscode/extensions/Shan.code-settings-sync-2.3.6/node_modules/github/lib/index.js:785:13)
    at /Users/blopez/.vscode/extensions/Shan.code-settings-sync-2.3.6/node_modules/github/lib/index.js:792:29
    at callCallback (/Users/blopez/.vscode/extensions/Shan.code-settings-sync-2.3.6/node_modules/github/lib/index.js:667:17)
    at IncomingMessage.<anonymous> (/Users/blopez/.vscode/extensions/Shan.code-settings-sync-2.3.6/node_modules/github/lib/index.js:723:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:440(anonymous function) @ shell.ts:353e.onUnexpectedError @ errors.ts:68r @ errors.ts:83t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:255[Extension Host] Empty value for parameter 'id': nullI.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
2messageService.ts:128Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:128e.show @ messageService.ts:107(anonymous function) @ mainThreadMessageService.ts:55n.Class.derive._oncancel @ winjs.base.raw.js:1641t.$showMessage @ mainThreadMessageService.ts:25e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by shanalikhan** [comment]
Please make sure you have posted a correct Github token as this happens when there is not valid github token,

**Comment by blopez2010** [comment]
Thanks, I haven't marked the **gist** option when creating the token.
