### ISSUE TITLE
local issuer certificate

### ISSUE THREAD

**Issue by chintan9** [shanalikhan/code-settings-sync#134]
**Visual Studio Code Version :** [ 1.7.1 ]
**Code Sync Settings Version :** [ 237 ]
**Operating System :** [ 10 November update ]
**Occurs On:** [ Download]
**Proxy Enabled:** [  No ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

`Uncaught Exception:  Error: unable to get local issuer certificate`
`extensionHost.ts:255[Extension Host] Windows_NT
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: unable to get local issuer certificateI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440unable to get local issuer certificate: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ shell.ts:440
extensionHost.ts:255[Extension Host] Uncaught Exception:  Error: socket hang upI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ shell.ts:440`

**Comment by shanalikhan** [comment]
Which extensions you have installed, 
Can you make your **GIST** public and share with me so i can see data coming from the GIST in downloading and generate this issue.

**Comment by chintan9** [comment]
https://gist.github.com/chintan9/c154de539fef7a4280e6c717b40e067a

**Comment by shanalikhan** [comment]
Its working fine for me, i have checked
following is the summary for the extenions :

```

EXTENSIONS ADDED : 
 
path-intellisense - Version :1.1.0 
Theme-Brogrammer - Version :0.0.3 
jsx - Version :0.0.1 
js-atom-grammar - Version :0.1.10 
vscode-eslint - Version :1.0.8 
vscode-JS-CSS-HTML-formatter - Version :0.2.1 
Spell - Version :0.8.6 
auto-close-tag - Version :0.3.4 
guides - Version :0.5.1 
vscode-icons - Version :4.0.0 
EditorConfig - Version :0.3.4 
vscode-svgviewer - Version :1.2.0 
```

**Comment by chintan9** [comment]
showing same error

**Comment by shanalikhan** [comment]
Can you try with the latest update of code and extension ?
Please update.

**Comment by chintan9** [comment]
okay I will let you know
