### ISSUE TITLE
Error "Extension 'vscode.git-ui' not found" after which sync stops.

### ISSUE THREAD

**Issue by akwala** [shanalikhan/code-settings-sync#1431]
🐛 **Describe the bug**  
This error is reported when I launch VSCodium on one of my two hosts. Happens consistently on that host only – the two hosts correspond to two users on the same Ubuntu device, so they use the same VSCodium installation but each has its own config and set of external extensions. 

Secondly, the download stops when the error happens – [apparently a separate issue](https://github.com/shanalikhan/code-settings-sync/issues/1302).

Adding `"git-ui"` to `"ignoreExtensions"` in `syncLocalSettings.json` prevents this error, as one would expect. However, shouldn't Settings Sync exclude it automatically, since `git-ui` is built into VSCode/VSCodium?

🌴 **~~Visual Studio Code~~ VSCodium Version :** [ 1.79.2 ] 
🌴 **Code Settings Sync Version :** [ 3.4.3 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ OSS ] 
🌴 **Operating System :** [ Kubuntu 22.04 ] 
🌴 **Occurs On:** [ Download ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ faab2abf9363cdd4b508005a47b13b3f ]

📰 **To Reproduce**
1. Configure Settings Sync on 2 hosts
2. Upload from host 1 – output shows `git-ui` among the extensions uploaded.
3. Download on host 2.
4. See error.

💪 **Expected behavior**

1. Settings Sync does not (try to) upload/download `git-ui` since it is a built-in extension.
2. Settings Sync downloads/syncs remaining extensions/settings.

📺 **Console Error Log** 
```
  ERR Extension 'vscode.git-ui' not found.: Error: Extension 'vscode.git-ui' not found.
    at handler (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2604:42800)
workbench.desktop.main.js:624   ERR [Extension Host] Error: Error: Error: Extension 'vscode.git-ui' not found.
	at /home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:22293
	at /home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:11611
	at Object.throw (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:11716)
	at s (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:10513)
workbench.desktop.main.js:97 [Extension Host] Error: Error: Error: Extension 'vscode.git-ui' not found.
	at /home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:22293
	at /home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:11611
	at Object.throw (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:11716)
	at s (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:10513)
I @ workbench.desktop.main.js:97
workbench.desktop.main.js:759 Sync: Error Logged In Console (Help menu > Toggle Developer Tools).

OUTPUT:
Realtime Extension Download Summary
--------------------
TOTAL EXTENSIONS : 2



[x] - EXTENSION: git-ui - INSTALLING
```
📺  **Additional context**
Will try to provide upon request.

**Comment by jinhua115** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
