### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by ChapaCactus** [shanalikhan/code-settings-sync#147]
**Visual Studio Code Version :** [ VERSION_HERE ]
**Code Sync Settings Version :** [ VERSION_HERE ]
**Operating System :** [ VERSION_HERE ]
**Occurs On:** [Upload / Download]
**Proxy Enabled:** [ Yes / No ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by ChapaCactus** [comment]
New Issue

**Comment by jouclar1** [comment]
Visual Studio Code Version : [1.7.2 ]
Code Sync Settings Version : [ 2.3.8]
Operating System : [ W7 ]
Occurs On: [Upload]
Proxy Enabled: [ No ]

**Comment by jouclar1** [comment]
Visual Studio Code Version : [1.7.2 ]
Code Sync Settings Version : [ 2.3.8]
Operating System : [ W7 ]
Occurs On: [Upload]
Proxy Enabled: [ No ]

Can't upload i get 

> Overwriting extension <<.j2>> to now point to mime <<text/x-html>>
mime.ts:59Overwriting extension <<.html>> to now point to mime <<text/x-html>>
mime.ts:59Overwriting extension <<.htm>> to now point to mime <<text/x-html>>
2mime.ts:59Overwriting extension <<.j2>> to now point to mime <<text/x-yaml>>
extensionHost.ts:255[Extension Host] Windows_NT
extensionHost.ts:255[Extension Host] vscode-icons is active!
extensionHost.ts:255[Extension Host] Windows_NT
extensionHost.ts:255[Extension Host] Error: connect ENOENT http_proxy=http://10.203.0.1:5187/
    at global.sendError (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:796:19)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:805:29
    at callCallback (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:680:17)
    at ClientRequest.<anonymous> (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:752:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at emitErr (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:83:11)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:94:9
    at Socket.onerror (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)
    at emitOne (events.js:96:13)I.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'id' of undefinedI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] TypeError: Cannot read property 'id' of undefined
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\out\src\githubService.js:75:24
    at global.sendError (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:798:13)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:805:29
    at callCallback (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:680:17)
    at ClientRequest.<anonymous> (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:752:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at emitErr (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:83:11)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:94:9
    at Socket.onerror (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440Cannot read property 'id' of undefined : TypeError: Cannot read property 'id' of undefined
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\out\src\githubService.js:75:24
    at global.sendError (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:798:13)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:805:29
    at callCallback (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:680:17)
    at ClientRequest.<anonymous> (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:752:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at emitErr (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:83:11)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:94:9
    at Socket.onerror (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)e.onUnexpectedError @ shell.ts:440
2extensionHost.ts:255[Extension Host] Empty value for parameter 'id': nullI.logExtensionHostMessage @ extensionHost.ts:255
2messageService.ts:128Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:128
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

**Comment by shanalikhan** [comment]
closing as invalid
