### ISSUE TITLE
Upload trouble

### ISSUE THREAD

**Issue by jouclar1** [shanalikhan/code-settings-sync#149]
Visual Studio Code Version : [1.7.2 ]
Code Sync Settings Version : [ 2.3.8]
Operating System : [ W7 ]
Occurs On: [Upload]
Proxy Enabled: [ No ]

Can't upload even after reseting

Shift + Alt + U doesn't work

> Overwriting extension <<.j2>> to now point to mime <<text/x-html>>
mime.ts:59Overwriting extension <<.html>> to now point to mime <<text/x-html>>
mime.ts:59Overwriting extension <<.htm>> to now point to mime <<text/x-html>>
2mime.ts:59Overwriting extension <<.j2>> to now point to mime <<text/x-yaml>>
extensionHost.ts:255[Extension Host] Windows_NT
extensionHost.ts:255[Extension Host] vscode-icons is active!
extensionHost.ts:255[Extension Host] Windows_NT
extensionHost.ts:255[Extension Host] Error: connect ENOENT http_proxy=http://10.203.0.1:5187/
    at global.sendError (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:796:19)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:805:29
    at callCallback (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:680:17)
    at ClientRequest.<anonymous> (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:752:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at emitErr (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:83:11)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:94:9
    at Socket.onerror (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)
    at emitOne (events.js:96:13)I.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'id' of undefinedI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255[Extension Host] TypeError: Cannot read property 'id' of undefined
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\out\src\githubService.js:75:24
    at global.sendError (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:798:13)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:805:29
    at callCallback (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:680:17)
    at ClientRequest.<anonymous> (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:752:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at emitErr (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:83:11)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:94:9
    at Socket.onerror (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)I.logExtensionHostMessage @ extensionHost.ts:255
shell.ts:440Cannot read property 'id' of undefined : TypeError: Cannot read property 'id' of undefined
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\out\src\githubService.js:75:24
    at global.sendError (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:798:13)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:805:29
    at callCallback (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:680:17)
    at ClientRequest.<anonymous> (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:752:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at emitErr (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:83:11)
    at C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\agent-base\agent.js:94:9
    at Socket.onerror (C:\Users\ahg302\.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)e.onUnexpectedError @ shell.ts:440
2extensionHost.ts:255[Extension Host] Empty value for parameter 'id': nullI.logExtensionHostMessage @ extensionHost.ts:255
2messageService.ts:128Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.

**Comment by shanalikhan** [comment]
can you share your settings.json file here ?

**Comment by jouclar1** [comment]
the file is empty

`// Placez vos paramètres dans ce fichier pour remplacer les paramètres par défaut
{
}`

**Comment by shanalikhan** [comment]
> extensionHost.ts:255[Extension Host] Error: connect ENOENT http_proxy=http://10.203.0.1:5187/
at global.sendError (C:\Users\ahg302.vscode\extensions\Shan.code-settings-sync-2.3.8\node_modules\github\lib\index.js:796:19)

U have proxy set either in code, or in system `http_proxy=http://10.203.0.1:5187/`

**Comment by jouclar1** [comment]
what can i do to make it run ?

**Comment by shanalikhan** [comment]
See the links below :)
https://fixedit.itxpress.biz/2014/10/08/unable-to-disable-windows-proxy-setting/

and try this in command 
```
npm config delete http-proxy
npm config delete https-proxy

npm config rm proxy
npm config rm https-proxy

set HTTP_PROXY=null
set HTTPS_PROXY=null
```
