### ISSUE TITLE
Self-signed certificate error

### ISSUE THREAD

**Issue by adbertram** [shanalikhan/code-settings-sync#219]
**Visual Studio Code Version :** [1.9]
**Code Settings Sync Version :** [ 2.4.3 ]
**Operating System :** [ Windows 10 ]
**Occurs On:** [ Setting Up]
**Proxy Enabled:** [ No ]
**GIst Id:** [ f4bc224a1cd16fd5c393f644b1b8c07412c0c5a6 ]

When setting up for the first time on a new Windows 10 machine, I input my GitHub token and immediately receive the stream of errors below. This DOES work find on my Mac though. I'm trying to download existing settings already there for the first time on Windows.

```
extensionHost.ts:282[Extension Host] Error: self signed certificate in certificate chain
    at global.sendError (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:838:19)
    at C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:849:29
    at callCallback (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:713:17)
    at ClientRequest.<anonymous> (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:791:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'id' of undefinedd.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
shell.ts:437Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\out\src\githubService.js:91:24
    at global.sendError (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:841:13)
    at C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:849:29
    at callCallback (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:713:17)
    at ClientRequest.<anonymous> (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:791:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)e.onUnexpectedError @ shell.ts:437(anonymous function) @ shell.ts:389e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
2messageService.ts:126Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:55n.Class.derive._oncancel @ winjs.base.raw.js:1641t.$showMessage @ mainThreadMessageService.ts:25e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282[Extension Host] TypeError: Cannot read property 'id' of undefined
    at C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\out\src\githubService.js:91:24
    at global.sendError (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:841:13)
    at C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:849:29
    at callCallback (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:713:17)
    at ClientRequest.<anonymous> (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:791:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
2extensionHost.ts:282[Extension Host] Empty value for parameter 'id': d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282[Extension Host] Error: self signed certificate in certificate chain
    at global.sendError (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:838:19)
    at C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:849:29
    at callCallback (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:713:17)
    at ClientRequest.<anonymous> (C:\Users\abertram\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:791:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
```

**Comment by shanalikhan** [comment]
This is due to your Github **connection** problem, the API doenst seem to connect with github properly in your machine and cause problem.

**Comment by jdshkolnik** [comment]
@shanalikhan I'm hitting this same error. It used to work on this machine yet now it doesn't. I don't think it can be easily dismissed as a local machine problem. I reset configuration, uninstalled plugin, deleted existing Gist and token, created new GitHub token, restarted Code, reinstalled plugin, attempted upload, put in new token...same error.

**Comment by shanalikhan** [comment]
@jdshkolnik create new token and connect with it using extension after 4-5 hours and update? :)

**Comment by jdshkolnik** [comment]
@shanalikhan Same error.

**Comment by shanalikhan** [comment]
@jdshkolnik Check the comment here for solution
https://github.com/shanalikhan/code-settings-sync/issues/257#issuecomment-287062228

**Comment by jdshkolnik** [comment]
@shanalikhan The latest comment seems to indicate the problem isn't resolved.

**Comment by shanalikhan** [comment]
Please check for version v2.6.1
and Update

**Comment by jdshkolnik** [comment]
Seems to be working now. Thanks.

**Comment by jdshkolnik** [comment]
It worked on one machine and then failed on a second.

**Comment by jdshkolnik** [comment]
Whichever I first connect can then update the gist but the second can't download even if I first reset the settings.

**Comment by shanalikhan** [comment]
and Second machine gives the same certificate failed exception ? on download

**Comment by jdshkolnik** [comment]
Yes.

**Comment by shanalikhan** [comment]
@jdshkolnik I have fixed this newer version. 
let me know if its still there.
