### ISSUE TITLE
[proxy] Error: socket hang up

### ISSUE THREAD

**Issue by lipkau** [shanalikhan/code-settings-sync#228]
**Visual Studio Code Version :** 1.9.1
**Code Settings Sync Version :** 2.4.3
**Operating System :** Windows 7
**Occurs On:** Setting Up
**Proxy Enabled:** Yes: `"http.proxy": "https://Lipkau:maPassword@server.company.com:8082"`
**GIst Id:** fb607b13563e9a031bd219ebad0501be

Error in console:
```
workbench.main.js:133 [Extension Host] Error: socket hang up
    at global.sendError (C:\lipkau\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:838:19)
    at C:\lipkau\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:849:29
    at callCallback (C:\lipkau\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:713:17)
    at ClientRequest.<anonymous> (C:\lipkau\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\github\lib\index.js:791:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at emitErr (C:\lipkau\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\agent-base\agent.js:83:11)
    at C:\lipkau\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\agent-base\agent.js:94:9
    at TLSSocket.onerror (C:\lipkau\.vscode\extensions\Shan.code-settings-sync-2.4.3\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)d.logExtensionHostMessage @ workbench.main.js:133
workbench.main.js:133 [Extension Host] Uncaught Exception:  TypeError: Cannot read property 'id' of undefinedd.logExtensionHostMessage @ workbench.main.js:133
```

**Comment by shanalikhan** [comment]
Can you try on the latest version 
and can you access the github from browser?

**Comment by lipkau** [comment]
I updated to `2.4.4` --> same error

I can access the gist.github.com from my browser.
I also can access it with Sublime Text's "GIST" plugin

**Comment by shanalikhan** [comment]
I wont be able to reproduce this error due to proxy environment settings.
Previously users sent me pull request to solve the proxy issues.

If you have time, you can download the code by placing the commands written here and send me pull request, i will accept that and hopefully extension will be more compatible with proxy environments.
https://github.com/shanalikhan/code-settings-sync#through-code

Thanks !

**Comment by shanalikhan** [comment]
as this was coming from github API.
can you try for this extension for code insiders i have updated the Github API and v2.6.0 that is available for insiders at the moment.

**Comment by SudoNova** [comment]
This issue persists

**Comment by SudoNova** [comment]
```log
workbench.desktop.main.js:71 [Extension Host] Sync : Connected with user : 'SudoNova'
workbench.desktop.main.js:603   ERR [Extension Host] HttpError: request to https://api.github.com/gists/bbbb246cabb26195fa4c2727cc1e6096 failed, reason: socket hang up
	at /home/sunova/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:761:1113
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
workbench.desktop.main.js:71 [Extension Host] HttpError: request to https://api.github.com/gists/bbbb246cabb26195fa4c2727cc1e6096 failed, reason: socket hang up	at /home/sunova/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:761:1113	at runMicrotasks (<anonymous>)	at processTicksAndRejections (internal/process/task_queues.js:93:5)
v @ workbench.desktop.main.js:71
$logExtensionHostMessage @ workbench.desktop.main.js:1523
_doInvokeHandler @ workbench.desktop.main.js:1523
_invokeHandler @ workbench.desktop.main.js:1523
_receiveRequest @ workbench.desktop.main.js:1523
_receiveOneMessage @ workbench.desktop.main.js:1523
(anonymous) @ workbench.desktop.main.js:1523
fire @ workbench.desktop.main.js:69
fire @ workbench.desktop.main.js:85
_receiveMessage @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
fire @ workbench.desktop.main.js:69
acceptChunk @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
_ @ workbench.desktop.main.js:2941
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:786 Sync: GIST NOT SAVED
onDidChangeNotification @ workbench.desktop.main.js:786
(anonymous) @ workbench.desktop.main.js:786
fire @ workbench.desktop.main.js:69
addNotification @ workbench.desktop.main.js:788
notify @ workbench.desktop.main.js:1576
(anonymous) @ workbench.desktop.main.js:1516
_showMessage @ workbench.desktop.main.js:1516
$showMessage @ workbench.desktop.main.js:1516
_doInvokeHandler @ workbench.desktop.main.js:1523
_invokeHandler @ workbench.desktop.main.js:1523
_receiveRequest @ workbench.desktop.main.js:1523
_receiveOneMessage @ workbench.desktop.main.js:1523
(anonymous) @ workbench.desktop.main.js:1523
fire @ workbench.desktop.main.js:69
fire @ workbench.desktop.main.js:85
_receiveMessage @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
fire @ workbench.desktop.main.js:69
acceptChunk @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
_ @ workbench.desktop.main.js:2941
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```
