### ISSUE TITLE
ERROR ! Logged In Console. Please open an issue in Github Repo.

### ISSUE THREAD

**Issue by GaryFurash** [shanalikhan/code-settings-sync#26]
**Visual Studio Code Version :** 0.10.11
**Code Sync Settings Version :** latest

Get message
ERROR ! Logged In Console. Please open an issue in Github Repo.

After enting git hub credential

**Comment by shanalikhan** [comment]
Are you sure you are using the latest version of extension. Please post the error log from the developer console.
I recently solved this issue in the last update #19

**Comment by GaryFurash** [comment]
Thanks for getting back to me.

I uninstalled and reinstalled - its using Shan.code-settings-sync-1.1.7:

how do I get the developer console open so I can send you the error log.

**Comment by GaryFurash** [comment]
[Plugin Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}
[Plugin Host] Uncaught Exception:  TypeError: Cannot read property 'id' of undefined
[Plugin Host] TypeError: Cannot read property 'id' of undefined
    at C:\Users\gffurash\.vscode\extensions\Shan.code-settings-sync-1.1.7\out\src\githubService.js:58:28
    at Object.proto.sendError (C:\Users\gffurash\.vscode\extensions\Shan.code-settings-sync-1.1.7\node_modules\github\api\v3.0.0\index.js:32:13)
    at C:\Users\gffurash\.vscode\extensions\Shan.code-settings-sync-1.1.7\node_modules\github\api\v3.0.0\gists.js:133:29
    at callCallback (C:\Users\gffurash\.vscode\extensions\Shan.code-settings-sync-1.1.7\node_modules\github\index.js:743:17)
    at IncomingMessage.<anonymous> (C:\Users\gffurash\.vscode\extensions\Shan.code-settings-sync-1.1.7\node_modules\github\index.js:793:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at C:\Users\gffurash\.vscode\extensions\Shan.code-settings-sync-1.1.7\out\src\githubService.js:58:28
    at Object.proto.sendError (C:\Users\gffurash\.vscode\extensions\Shan.code-settings-sync-1.1.7\node_modules\github\api\v3.0.0\index.js:32:13)
    at C:\Users\gffurash\.vscode\extensions\Shan.code-settings-sync-1.1.7\node_modules\github\api\v3.0.0\gists.js:133:29
    at callCallback (C:\Users\gffurash\.vscode\extensions\Shan.code-settings-sync-1.1.7\node_modules\github\index.js:743:17)
    at IncomingMessage.<anonymous> (C:\Users\gffurash\.vscode\extensions\Shan.code-settings-sync-1.1.7\node_modules\github\index.js:793:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:442:9)
    at process._tickCallback (node.js:356:17)
ERROR ! Logged In Console. Please open an issue in Github Repo.

**Comment by GaryFurash** [comment]
Whops, you can close it out - I reset everything and started from scratch and it worke dgreat. Thanks!!!!!

**Comment by shanalikhan** [comment]
Oh great! Good to know you have solved it :)
