### ISSUE TITLE
Error using the extension

### ISSUE THREAD

**Issue by Jakub41** [shanalikhan/code-settings-sync#260]
**Visual Studio Code Version :** [ 1.10.2 ]
**Code Settings Sync Version :** [ last one just installed ]
**Operating System :** [ Mac X ]
**Occurs On:** [Shift + Alt + U ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ 925fea35a122b2e979ef5610016980f2f4f23fb7 ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

Hello,

I have this error when trying to use the extension:
Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.

Hope there is a solution about it

Thank you

**Comment by Jakub41** [comment]
Yes sure check screenshot, please 
![Uploading Screen Shot 2017-03-17 at 18.36.15.png…]()

**Comment by Jakub41** [comment]
If the screen shot is not opening this is the copy of it is in the console:
extensionHost.ts:282 [Extension Host] Darwin
extensionHost.ts:282 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
extensionHost.ts:282 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282 [Extension Host] Uncaught Exception:  TypeError: Cannot read property 'id' of undefinedd.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282 [Extension Host] TypeError: Cannot read property 'id' of undefined
    at /Users/jakublemiszewski/.vscode/extensions/Shan.code-settings-sync-2.5.1/out/src/githubService.js:91:24
    at global.sendError (/Users/jakublemiszewski/.vscode/extensions/Shan.code-settings-sync-2.5.1/node_modules/github/lib/index.js:841:13)
    at /Users/jakublemiszewski/.vscode/extensions/Shan.code-settings-sync-2.5.1/node_modules/github/lib/index.js:849:29
    at callCallback (/Users/jakublemiszewski/.vscode/extensions/Shan.code-settings-sync-2.5.1/node_modules/github/lib/index.js:713:17)
    at IncomingMessage.<anonymous> (/Users/jakublemiszewski/.vscode/extensions/Shan.code-settings-sync-2.5.1/node_modules/github/lib/index.js:774:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
2extensionHost.ts:282 [Extension Host] Empty value for parameter 'id': d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
shell.ts:426 Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at /Users/jakublemiszewski/.vscode/extensions/Shan.code-settings-sync-2.5.1/out/src/githubService.js:91:24
    at global.sendError (/Users/jakublemiszewski/.vscode/extensions/Shan.code-settings-sync-2.5.1/node_modules/github/lib/index.js:841:13)
    at /Users/jakublemiszewski/.vscode/extensions/Shan.code-settings-sync-2.5.1/node_modules/github/lib/index.js:849:29
    at callCallback (/Users/jakublemiszewski/.vscode/extensions/Shan.code-settings-sync-2.5.1/node_modules/github/lib/index.js:713:17)
    at IncomingMessage.<anonymous> (/Users/jakublemiszewski/.vscode/extensions/Shan.code-settings-sync-2.5.1/node_modules/github/lib/index.js:774:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:426(anonymous function) @ shell.ts:383e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
2messageService.ts:126 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by shanalikhan** [comment]
Reset extension settings
Generate new token and then apply

**Comment by Jakub41** [comment]
Ok and for reset the extension setting how I have to do it.
I need just to uninstall and install again?

**Comment by shanalikhan** [comment]
Please read the complete readme for once
https://github.com/shanalikhan/code-settings-sync#reset-token--gist-settings

**Comment by Jakub41** [comment]
I resolved thank you :)
