### ISSUE TITLE
"SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol" exception behind corporate proxy

### ISSUE THREAD

**Issue by SuperV1234** [shanalikhan/code-settings-sync#263]
**Visual Studio Code Version :** [ 1.11.0-insider ]
**Code Settings Sync Version :** [ 2.6.1 ]
**Operating System :** [ Windows 7 Enterprise ]
**Occurs On:** [ Download ]
**Proxy Enabled:** [ Yes ]
**GIst Id:** [ e60a40856f52df7484488500c80638dc ]

My proxy is set up correctly in VSCode (i.e. I can download/update extensions from the extensions tab).
I get this error when trying to download my synced settings:

![err](https://cloud.githubusercontent.com/assets/918661/24201678/a8d33cec-0f08-11e7-95c2-8ac9b06eaf09.PNG)

As text: 

```
Extension Host] Error: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:c:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:

    at global.sendError (C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\github\lib\index.js:839:19)
    at C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\github\lib\index.js:850:29
    at callCallback (C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\github\lib\index.js:714:17)
    at ClientRequest.<anonymous> (C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\github\lib\index.js:792:17)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at emitErr (C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\agent-base\agent.js:83:11)
    at C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\agent-base\agent.js:94:9
    at TLSSocket.onerror (C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)
    at emitOne (events.js:96:13)
2extensionHost.ts:282 [Extension Host] Error: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:c:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:

    at global.sendError (C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\github\lib\index.js:839:19)
    at C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\github\lib\index.js:850:29
    at callCallback (C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\github\lib\index.js:714:17)
    at ClientRequest.<anonymous> (C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\github\lib\index.js:792:17)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at emitErr (C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\agent-base\agent.js:83:11)
    at C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\agent-base\agent.js:94:9
    at TLSSocket.onerror (C:\Users\vromeo5\.vscode-insiders\extensions\Shan.code-settings-sync-2.6.1\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)
    at emitOne (events.js:96:13)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282 [Extension Host] ApplicationInsights:Sender [Object]
```

**Comment by andrewkboyd** [comment]
I have the same issue. I only had a brief moment to look into it but it looks like an issue with the plugin not respecting the 'http.proxyStrictSSL' setting. In my case at least, I have to set that to false because we have our own PKI.

My guess is that http is not trusting the cert by default.

**Comment by shanalikhan** [comment]
Will release the fix in upcoming version.

**Comment by shanalikhan** [comment]
I have published v.2.6.2. 
please let me know if error still persists.

**Comment by SuperV1234** [comment]
Seems to work now, thanks!
