### ISSUE TITLE
Error during set-up(upload), after update to ver 262.

### ISSUE THREAD

**Issue by BladeMight** [shanalikhan/code-settings-sync#279]
**Visual Studio Code Version :** [ 1.10 stable & 1.11-insider ]
**Code Settings Sync Version :** [ 262 ]
**Operating System :** [ Windows 7 Ultimate x64 ]
**Occurs On:** [Upload]
**Proxy Enabled:** [ No ]
**GIst Id:** [ no ]

It fails with error;

<details><summary>Error in console:</summary>

```lua
extensionHost.ts:284 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}d.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] Uncaught Exception:  TypeError: Cannot read property 'data' of undefinedd.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] TypeError: Cannot read property 'data' of undefined
    at D:\Program\Utils\Code\.vscode\extensions\Shan.code-settings-sync-2.6.2\out\src\githubService.js:100:24
    at global.sendError (D:\Program\Utils\Code\.vscode\extensions\Shan.code-settings-sync-2.6.2\node_modules\github\lib\index.js:856:13)
    at D:\Program\Utils\Code\.vscode\extensions\Shan.code-settings-sync-2.6.2\node_modules\github\lib\index.js:864:29
    at callCallback (D:\Program\Utils\Code\.vscode\extensions\Shan.code-settings-sync-2.6.2\node_modules\github\lib\index.js:728:17)
    at IncomingMessage.<anonymous> (D:\Program\Utils\Code\.vscode\extensions\Shan.code-settings-sync-2.6.2\node_modules\github\lib\index.js:789:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)d.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
shell.ts:475 Cannot read property 'data' of undefined: TypeError: Cannot read property 'data' of undefined
    at D:\Program\Utils\Code\.vscode\extensions\Shan.code-settings-sync-2.6.2\out\src\githubService.js:100:24
    at global.sendError (D:\Program\Utils\Code\.vscode\extensions\Shan.code-settings-sync-2.6.2\node_modules\github\lib\index.js:856:13)
    at D:\Program\Utils\Code\.vscode\extensions\Shan.code-settings-sync-2.6.2\node_modules\github\lib\index.js:864:29
    at callCallback (D:\Program\Utils\Code\.vscode\extensions\Shan.code-settings-sync-2.6.2\node_modules\github\lib\index.js:728:17)
    at IncomingMessage.<anonymous> (D:\Program\Utils\Code\.vscode\extensions\Shan.code-settings-sync-2.6.2\node_modules\github\lib\index.js:789:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:475(anonymous function) @ shell.ts:435e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
2messageService.ts:126 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
2extensionHost.ts:284 [Extension Host] Empty value for parameter 'id': d.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```
</details>

**Comment by shanalikhan** [comment]
Try with Resetting the extension and then putting token again
Or generate new token.

**Comment by BladeMight** [comment]
> Resetting the extension

You mean reinstall? If so it didn't work, i also tried to create new `.vscode` folder but it too didn't work. 
But it worked after i created new `%AppData%\Code` folder(and renamed my old), so i think there was some wrong settings, i restored my settings by copying file `settings.json` from my old `%AppData%\Code` folder.
So for me it is fixed.
