### ISSUE TITLE
Errors on sync download

### ISSUE THREAD

**Issue by Nikki1993** [shanalikhan/code-settings-sync#313]
**Visual Studio Code Version :** [ 1.11.2 ]
**Code Settings Sync Version :** [ 2.6.2 ]
**Operating System :** [ Windows 10 Annuversary Update Version 1703 Build 15063.250]
**Occurs On:** [ Download ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ 68ccfaa8b37a553f405085e856a3369f ]

```
[Extension Host] C:\Users\nikit\AppData\Roaming/Code/User/settings.json
[Extension Host] C:\Users\nikit\AppData\Roaming/Code/User/snippets/html.json
[Extension Host] C:\Users\nikit\AppData\Roaming/Code/User/snippets/json.json
[Extension Host] C:\Users\nikit\AppData\Roaming/Code/User/snippets/plaintext.json
[Extension Host] C:\Users\nikit\AppData\Roaming/Code/User/snippets/typescript.json
[Extension Host] C:\Users\nikit\AppData\Roaming/Code/User/snippets/yaml.json
[Extension Host] C:\Users\nikit\AppData\Roaming/Code/User/vsicons.settings.json
[Extension Host] Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:564:26)
Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.
```

**Comment by shanalikhan** [comment]
Can you try on 2.7
Is this happening every time ?

**Comment by Nikki1993** [comment]
Seems to be fixed in the latest version. Previously error occurred on each download.
