### ISSUE TITLE
command 'extension.updateSettings' not found

### ISSUE THREAD

**Issue by folkrav** [shanalikhan/code-settings-sync#329]
**Visual Studio Code Version :** 1.12.2
**Code Settings Sync Version :** 2.8.0
**Operating System :** OS X El Capitan 10.11.5
**Occurs On:** Upload
**Proxy Enabled:** No
**GIst Id:** 1838cdb29be8483a3525c8bc6f16feb1

Simply trying to upload settings! Tried removing and re-adding. Getting this in dev console:

```
[Extension Host] Here is the error stack:  Error: Cannot find module '/Users/js/.vscode/extensions/Shan.code-settings-sync-2.8.0/out/src/extension'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Y.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:366378)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.s [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:25886)
    at d (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:367582)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:372569
    at n.Class.derive._oncancel.then (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:69267)
    at t._doActualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:372529)
```

**Comment by folkrav** [comment]
Somehow removing and re-adding a second time seemed to have fixed this. Sorry for the useless issue!
