### ISSUE TITLE
Error when trying to sync for first time

### ISSUE THREAD

**Issue by xabikos** [shanalikhan/code-settings-sync#36]
**Visual Studio Code Version :**  1.1.1
**Code Sync Settings Version :**  1.2.3 
**Operating System :**  Windows 7

After installation and when I try to sync for first time I get the following error

`
Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.2.3\out\src\githubService.js:61:28
    at Object.proto.sendError (C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.2.3\node_modules\github\api\v3.0.0\index.js:32:13)
    at C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.2.3\node_modules\github\api\v3.0.0\gists.js:133:29
    at callCallback (C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.2.3\node_modules\github\index.js:743:17)
    at IncomingMessage.<anonymous> (C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.2.3\node_modules\github\index.js:793:25)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ workbench.main.js:117
workbench.main.js:90ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo.e.doShow @ workbench.main.js:90
`

**Comment by shanalikhan** [comment]
can you please verify this error in the new version ?

**Comment by xabikos** [comment]
Unfortunately the error is still there for version 1.3.0

`
workbench.main.js:91[Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}(anonymous function) @ workbench.main.js:91
workbench.main.js:91[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'id' of undefined(anonymous function) @ workbench.main.js:91
workbench.main.js:91[Extension Host] TypeError: Cannot read property 'id' of undefined
    at C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.3.0\out\src\githubService.js:61:28
    at global.sendError (C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:755:13)
    at C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:762:29
    at callCallback (C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:639:17)
    at IncomingMessage.<anonymous> (C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:694:25)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ workbench.main.js:91
workbench.main.js:117Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.3.0\out\src\githubService.js:61:28
    at global.sendError (C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:755:13)
    at C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:762:29
    at callCallback (C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:639:17)
    at IncomingMessage.<anonymous> (C:\Users\karypch\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:694:25)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ workbench.main.js:117
workbench.main.js:90ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo.
`

**Comment by shanalikhan** [comment]
actually this error appears due to invalid token.
You need to reset your extension settings and try again posting new token

**Comment by xabikos** [comment]
Yes the reset settings fixed the problem. Thanks

**Comment by Lutreer** [comment]
how to reset settings of this extension

![20160801104138](https://cloud.githubusercontent.com/assets/8281336/17283997/22147850-57e9-11e6-9023-cb546f4323da.png)
