### ISSUE TITLE
Don't work Upload settings in Ubuntu 14

### ISSUE THREAD

**Issue by Hydrock** [shanalikhan/code-settings-sync#366]
**Visual Studio Code Version :** 1.14.1
**Code Settings Sync Version :** 2.8.2
**Operating System :** Ubuntu 14
**Occurs On:** Upload
**Proxy Enabled:** No
**GIst Id:** [ ID_HERE ]

Don't work Upload settings in Ubuntu 14

Link to video about my problem
https://www.youtube.com/watch?v=xbkvkpV9u2I&feature=youtu.be

**Comment by phito** [comment]
can confirm, doesn't work for me either

**Comment by shanalikhan** [comment]
What is the exception in the developer console

**Comment by lioujheyu** [comment]
I have the same issue in Ubuntu 16.04. Here is the log in the developer console
```
spawn EACCES: Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at module.exports (/home/jliou4/.vscode/extensions/Shan.code-settings-sync-2.8.2/node_modules/opn/index.js:74:26)
    at Commons.<anonymous> (/home/jliou4/.vscode/extensions/Shan.code-settings-sync-2.8.2/out/src/commons.js:189:25)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jliou4/.vscode/extensions/Shan.code-settings-sync-2.8.2/out/src/commons.js:4:58)
```

**Comment by burgerga** [comment]
Same issue with vscode 1.14.1 in Manjaro (Arch), so maybe a more general problem?

**Comment by Hydrock** [comment]
lioujheyu - Absolutely the same

**Comment by GJKrupa** [comment]
Likewise (Ubuntu 16.04).  If I edit the local configuration for the extension and insert the token it seems to work.

**Comment by lioujheyu** [comment]
The solution of adding execution permission to `~/.vscode/extensions/Shan.code-settings-sync-2.8.2/node_modules/opn/xdg-open` from #327 works for me. I guess they are the same issues.

**Comment by shanalikhan** [comment]
Duplicate : https://github.com/shanalikhan/code-settings-sync/issues/352

**Comment by Hydrock** [comment]
try - chmod +x /home/<desktop-username>/.vscode/extensions/<settings-sync-folder-name>/node_modules/opn/xdg-open
