### ISSUE TITLE
Unable to sync behind my company using Microsoft ISA Server

### ISSUE THREAD

**Issue by cboillat** [shanalikhan/code-settings-sync#399]
**Visual Studio Code Version :** 1.16.1
**Code Settings Sync Version :** 2.8.3
**Operating System :** Windows 10 Enterprise build 1703
**Occurs On:** [Upload / Download / Help Configuring ] Download
**Proxy Enabled:** [ Yes / No ] I tried Yes and No
**GIst Id:** e9b9a2ab8ed400a8dea8b6b6cb022b33

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

Here is what the console spit  : 

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] Error: connect ENOENT hepisa.hep-bejune.ch
	at module.exports.sendError (C:\Users\clement.boillat\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\github\lib\index.js:854:19)
	at C:\Users\clement.boillat\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\github\lib\index.js:865:29
	at callCallback (C:\Users\clement.boillat\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\github\lib\index.js:728:17)
	at ClientRequest.<anonymous> (C:\Users\clement.boillat\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\github\lib\index.js:807:17)
	at emitOne (events.js:96:13)
	at ClientRequest.emit (events.js:191:7)
	at emitErr (C:\Users\clement.boillat\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\agent-base\agent.js:88:11)
	at C:\Users\clement.boillat\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\agent-base\agent.js:99:9
	at Socket.onerror (C:\Users\clement.boillat\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\github\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at emitErrorNT (net.js:1283:8)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
﻿
I spent hours trying to configure the proxy but nothing works. Any idea or steps to follow ?

**Comment by shanalikhan** [comment]
I might not be able to reproduce at my end due to connection.
> I spent hours trying to configure the proxy but nothing works. 

What you can do is hit the [commands](https://github.com/shanalikhan/code-settings-sync#through-code) and run the extension and debug it and send me pull request, i will accept and publish new version if it helped you.

**Comment by cboillat** [comment]
Ok,  thank you for your answer.
I'll check your commands and maybe send a pull request if I find something.
