### ISSUE TITLE
Error  after setup access token

### ISSUE THREAD

**Issue by Quekie** [shanalikhan/code-settings-sync#485]
**Visual Studio Code Version :** [ 1.19.2]
**Code Settings Sync Version :** [ 2.8.7]
**Operating System :** [ windows10]
**Occurs On:** [Upload]
**Proxy Enabled:** [ No ]
**GIst Id:** [ null ]
after i input access token , i try to upload first time , then i got this two error ;

 Error: getaddrinfo ENOTFOUND 1080 1080:80
	at module.exports.__dirname.sendError (C:\Users\ch\.vscode\extensions\Shan.code-settings-sync-2.8.7\node_modules\github\lib\index.js:854:19)
	at C:\Users\ch\.vscode\extensions\Shan.code-settings-sync-2.8.7\node_modules\github\lib\index.js:865:29
	at callCallback (C:\Users\ch\.vscode\extensions\Shan.code-settings-sync-2.8.7\node_modules\github\lib\index.js:728:17)
	at ClientRequest.<anonymous> (C:\Users\ch\.vscode\extensions\Shan.code-settings-sync-2.8.7\node_modules\github\lib\index.js:807:17)
	at emitOne (events.js:96:13)
	at ClientRequest.emit (events.js:191:7)
	at emitErr (C:\Users\ch\.vscode\extensions\Shan.code-settings-sync-2.8.7\node_modules\agent-base\agent.js:88:11)
	at C:\Users\ch\.vscode\extensions\Shan.code-settings-sync-2.8.7\node_modules\agent-base\agent.js:99:9
	at Socket.onerror (C:\Users\ch\.vscode\extensions\Shan.code-settings-sync-2.8.7\node_modules\github\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)
	at emitOne (events.js:96:13)

**Comment by shanalikhan** [comment]
can you try on other network ?

**Comment by Quekie** [comment]
it seems  The GFW problem . china can't access gist
