### ISSUE TITLE
Extension is not using the proxy 

### ISSUE THREAD

**Issue by afnpires** [shanalikhan/code-settings-sync#50]
**Visual Studio Code Version :** [ 1.2.1 ]
**Code Sync Settings Version :** [ 1.3.0 ]
**Operating System :** [ Windows 7 ]

The extension is not using the defined proxy in settings resulting a timeout.

`[Extension Host] Error: connect ETIMEDOUT 192.30.253.116:443
    at global.sendError (C:\Users\alexandre.pires\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:753:19)
    at C:\Users\alexandre.pires\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:762:29
    at callCallback (C:\Users\alexandre.pires\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:639:17)
    at ClientRequest.<anonymous> (C:\Users\alexandre.pires\.vscode\extensions\Shan.code-settings-sync-1.3.0\node_modules\github4\lib\index.js:710:17)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at TLSSocket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at emitErrorNT (net.js:1253:8)`

**Comment by shanalikhan** [comment]
can you update the extension and let me know if issue persist

**Comment by Naramsim** [comment]
I'm experiencing the same issue above, I'm behind a proxy, and the extensions times out when downloading the settings.

**Comment by Naramsim** [comment]
@shanalikhan @afnpires, any updates on how make it work?

**Comment by shanalikhan** [comment]
actually i dont have environment to test proxy. although extension currently handles proxy
But i'm always looking forward to improve the proxy support.

If there is still a problem, you can run the extension locally from code and send me pull request, i will accept and release new version.
