### ISSUE TITLE
command 'extension.downloadSettings' not found

### ISSUE THREAD

**Issue by rudfoss** [shanalikhan/code-settings-sync#549]
**Visual Studio Code Version :** 1.23
**Code Settings Sync Version :** 2.9.2
**Operating System :** Windows 10 1709
**Occurs On:** Download (any command)
**Proxy Enabled:** No
**GIst Id:** b52e4edddc8331530912657066e329f3

When trying to download I get an error from VSCode

    command 'extension.downloadSettings' not found

None of the other commands work either. It seems it's trying to access a folder called `Code - OSS`, but I only have the regular Code folder on my machine. I've tried reinstalling VSCode, Settings Sync and removing the .code folder as well as the %appData%/Roaming/Code folder, but the error persists.

```
Error: ENOENT: no such file or directory, stat 'C:\Users\thomas.rudfoss\AppData\Roaming\Code - OSS'
	at fs.statSync (fs.js:973:11)
	at Object.fs.statSync (ELECTRON_ASAR.js:280:16)
	at new Environment (C:\Users\thomas.rudfoss\.vscode\extensions\Shan.code-settings-sync-2.9.2\out\src\environmentPath.js:75:20)
	at C:\Users\thomas.rudfoss\.vscode\extensions\Shan.code-settings-sync-2.9.2\out\src\extension.js:23:18
	at Generator.next (<anonymous>)
	at C:\Users\thomas.rudfoss\.vscode\extensions\Shan.code-settings-sync-2.9.2\out\src\extension.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\thomas.rudfoss\.vscode\extensions\Shan.code-settings-sync-2.9.2\out\src\extension.js:3:12)
	at activate (C:\Users\thomas.rudfoss\.vscode\extensions\Shan.code-settings-sync-2.9.2\out\src\extension.js:20:12)
	at Function.t._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:592)
	at Function.t._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:271)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:720:336
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:654)
	at K.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:868)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:654)
	at K.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:868)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at e.resolveOk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:525:85)
	at e._receiveReply (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:227)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:524)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:596:384
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:463
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

**Comment by shanalikhan** [comment]
are you still facing this problem ?
Try reinstalling the extension

**Comment by rudfoss** [comment]
Hi, yeah. I tried reinstalling both VSCode as well as the plugin. Both with and without removing the settings directory at %appdata% and VSCode inside my user folder. Let me know if you need additional debugging information. It seems the extension thinks I'm using the OSS version of VSCode for some reason. It works on some of my machines, but not all. All of them are running Windows 10 x64.

**Comment by zelljhos** [comment]
i have the same problem!! i run this in MacOs HighSierra 10.13.4

**Comment by CarrierDirectRoss** [comment]
Same issue on High Sierra!

**Comment by dbossard** [comment]
all users having "oss" in their name (@rudfoss, @CarrierDirectRoss, and me, as dbossard) are doomed :) :
in environmentPath.js : 
this.isOss = /oss/.test(context.asAbsolutePath(""));
=> a quick and dirty fix is to change the regexp to /\boss\b/ (but a proper path check would be better)

**Comment by flacrosse** [comment]
me too thanks :)

**Comment by m-rossi** [comment]
:(

**Comment by ladarit** [comment]
@dbossard regards!)

**Comment by blackinitial** [comment]
@dbossard where is location of environmentPath.js ??

**Comment by joerossetter** [comment]
@blackinitial on a Mac - /Users/{user}/.vscode/extensions/Shan.code-settings-sync-2.9.2/out/src

**Comment by shanalikhan** [comment]
Thanks @rudfoss for the PR
I will release new version in few days.

**Comment by valentinocossar** [comment]
Any updates about this fix? Thank you.

**Comment by shanalikhan** [comment]
Fixed, Release
Let me know if there is any problem

**Comment by seanlook** [comment]
It seems happen again in the latest version 1.30.1:
```
command 'extension.otherOptions' not found
```

**Comment by lencshu** [comment]
> It seems happen again in the latest version 1.30.1:
> 
> ```
> command 'extension.otherOptions' not found
> ```

Me too,
Version 1.31.0
