### ISSUE TITLE
Error while on boarding second system

### ISSUE THREAD

**Issue by aaroncrespo** [shanalikhan/code-settings-sync#61]
Looks like an incomplete on boarding but it should provide a better error

**Visual Studio Code Version :** [ 1.4.0 ]
**Code Sync Settings Version :** [ 1.6.3 ]
**Operating System :** [ 10.11.6]

Please make sure to write the versions and console logged error picture or copied text.

```log
[Extension Host] Darwin
[Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'id' of undefined
[Extension Host] TypeError: Cannot read property 'id' of undefined
    at /Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/out/src/githubService.js:64:28
    at global.sendError (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:755:13)
    at /Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:762:29
    at callCallback (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:639:17)
    at IncomingMessage.<anonymous> (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:694:25)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at /Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/out/src/githubService.js:64:28
    at global.sendError (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:755:13)
    at /Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:762:29
    at callCallback (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:639:17)
    at IncomingMessage.<anonymous> (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:694:25)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo using 'Sync : Open Issue' command.
[Extension Host] Darwin
[Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'id' of undefined
[Extension Host] TypeError: Cannot read property 'id' of undefined
    at /Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/out/src/githubService.js:64:28
    at global.sendError (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:755:13)
    at /Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:762:29
    at callCallback (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:639:17)
    at IncomingMessage.<anonymous> (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:694:25)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at /Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/out/src/githubService.js:64:28
    at global.sendError (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:755:13)
    at /Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:762:29
    at callCallback (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:639:17)
    at IncomingMessage.<anonymous> (/Users/{me}/.vscode/extensions/Shan.code-settings-sync-1.6.3/node_modules/github4/lib/index.js:694:25)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo using 'Sync : Open Issue' command.

```

**Comment by shanalikhan** [comment]
> {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

This error shows the invalid token entered. You can reset the settings and try with new github token , save in github and then copy that in extension.

**Comment by aaroncrespo** [comment]
Yeah that's what I did after I read the logs, but the error message displayed to the user also said to open an issue.

**Comment by shanalikhan** [comment]
Yes some users don't know its problem of their side so its better to open the issue so they know the solution
