### ISSUE TITLE
Error console logged - Cant download/upload

### ISSUE THREAD

**Issue by roroland** [shanalikhan/code-settings-sync#638]
🐛 **Describe the bug** 

Cant download my gist to sync, have successfully set it on a mac before

Error log:
workbench.main.js:sourcemap:276 [Extension Host] Error :/Code
t.log @ workbench.main.js:sourcemap:276
t._logExtensionHostMessage @ workbench.main.js:sourcemap:3151
(anonymous) @ workbench.main.js:sourcemap:3147
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
workbench.main.js:sourcemap:276 [Extension Host] Error: ENOENT: no such file or directory, stat '/home/rodrigo/.config/Code'
	at fs.statSync (fs.js:954:11)
	at Object.fs.statSync (ELECTRON_ASAR.js:302:16)
	at Object.statSync (/home/rodrigo/.var/app/com.visualstudio.code/data/vscode/extensions/shan.code-settings-sync-3.1.2/node_modules/graceful-fs/polyfills.js:297:22)
	at new Environment (/home/rodrigo/.var/app/com.visualstudio.code/data/vscode/extensions/shan.code-settings-sync-3.1.2/out/src/environmentPath.js:89:20)
	at Sync.<anonymous> (/home/rodrigo/.var/app/com.visualstudio.code/data/vscode/extensions/shan.code-settings-sync-3.1.2/out/src/sync.js:261:25)
	at Generator.next (<anonymous>)
	at /home/rodrigo/.var/app/com.visualstudio.code/data/vscode/extensions/shan.code-settings-sync-3.1.2/out/src/sync.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (/home/rodrigo/.var/app/com.visualstudio.code/data/vscode/extensions/shan.code-settings-sync-3.1.2/out/src/sync.js:3:12)
	at Sync.download (/home/rodrigo/.var/app/com.visualstudio.code/data/vscode/extensions/shan.code-settings-sync-3.1.2/out/src/sync.js:260:16)
	at e._executeContributedCommand (/app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:726:706)
	at e.$executeContributedCommand (/app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:727:212)
	at e._doInvokeHandler (/app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/app/extra/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
t.log @ workbench.main.js:sourcemap:276
t._logExtensionHostMessage @ workbench.main.js:sourcemap:3151
(anonymous) @ workbench.main.js:sourcemap:3147
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
workbench.main.js:sourcemap:276 [Extension Host] TypeError: Cannot read property 'token' of undefined
	at Commons.<anonymous> (/home/rodrigo/.var/app/com.visualstudio.code/data/vscode/extensions/shan.code-settings-sync-3.1.2/out/src/commons.js:218:29)
	at Generator.next (<anonymous>)
	at fulfilled (/home/rodrigo/.var/app/com.visualstudio.code/data/vscode/extensions/shan.code-settings-sync-3.1.2/out/src/commons.js:4:58)
	at <anonymous>
t.log @ workbench.main.js:sourcemap:276
t._logExtensionHostMessage @ workbench.main.js:sourcemap:3151
(anonymous) @ workbench.main.js:sourcemap:3147
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
workbench.main.js:sourcemap:2407 Sync : Error Logged In Console (Help menu > Toggle Developer Tools).
t.onDidNotificationChange @ workbench.main.js:sourcemap:2407
(anonymous) @ workbench.main.js:sourcemap:2407
e.fire @ workbench.main.js:sourcemap:175
t.notify @ workbench.main.js:sourcemap:2400
t.notify @ workbench.main.js:sourcemap:3483
e._showMessage @ workbench.main.js:sourcemap:3204
e._showMessage @ workbench.main.js:sourcemap:3203
e.$showMessage @ workbench.main.js:sourcemap:3203
e._doInvokeHandler @ workbench.main.js:sourcemap:3235
e._invokeHandler @ workbench.main.js:sourcemap:3235
e._receiveRequest @ workbench.main.js:sourcemap:3234
e._receiveOneMessage @ workbench.main.js:sourcemap:3233
(anonymous) @ workbench.main.js:sourcemap:3232
e.fire @ workbench.main.js:sourcemap:175
a @ workbench.main.js:sourcemap:311
n._socketDataListener @ workbench.main.js:sourcemap:311
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594

🌴 **Visual Studio Code Version :** [ 1.27.1 ] 
🌴 **Code Settings Sync Version :** [ 3.1.2] 
🌴 **Operating System :** [ Linux Mint 18.3 ] 
🌴 **Occurs On:** [Upload / Download ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ d7c1af12cdb123daa54616df5217b54b1db454dc ]

thanks

**Comment by KrzysztofGastolek** [comment]
I have the same problem, but on windows.

**Comment by hl2guide** [comment]
Me too on Windows, trying a first time sync (Shift+Alt+U) and I get:

Sync : Error Logged In Console

Cannot read property 'token' of undefined
	at Commons.<anonymous> (C:\Portable Software\PortableApps\PortableApps\Visual Studio Code\data\extensions\shan.code-settings-sync-3.1.2\out\src\commons.js:218:29)

no ability to type in my token to get a gist ID.

**Comment by shanalikhan** [comment]
> at Commons. (C:\Portable Software\PortableApps\PortableApps\Visual Studio Code\data\extensions\shan.code-settings-sync-3.1.2\out\src\commons.js:218:29)

@hl2guide Settings sync doenst support Portable Mode. Subscribe to this https://github.com/shanalikhan/code-settings-sync/issues/331


@roroland how you install visual studio code ? via Flatpak  ?

**Comment by roroland** [comment]
Hi @shanalikhan , yes I fixed by install Visual Studio from the official package on their web. I previously installed from Mint's software manager, I wrongly suppose that it was the same version than the official...
Then I reinstall the extension and all worked as expected.

Thanks
