### ISSUE TITLE
[Extension Host] TypeError: Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by EnvySky** [shanalikhan/code-settings-sync#692]
When I Upload Your Settings For the first time I saw the error:
```
/C:/VSCode/resources/app/out/vs/workbench/workbench.main.js:282 
[Extension Host] TypeError: Cannot read property 'token' of undefined
	at Commons.<anonymous> (C:\VSCode\data\extensions\shan.code-settings-sync-3.2.0\out\src\commons.js:216:29)
	at Generator.next (<anonymous>)
	at fulfilled (C:\VSCode\data\extensions\shan.code-settings-sync-3.2.0\out\src\commons.js:4:58)
	at <anonymous>
```
I'm using VSCode **win32-x64-1.28.2** win32-x64-1.28.2 on Windows10

How can I resolve this? Thanks

**Comment by EnvySky** [comment]
Sorry, my mistake.
