### ISSUE TITLE
Reset not working using portable mode

### ISSUE THREAD

**Issue by Ash258** [shanalikhan/code-settings-sync#696]
🐛 **Describe the bug**  
When trying to reset and again upload settings, error occoured.

🌴 **Visual Studio Code Version :** 1.29.0-insider@4a29bd3731e40c07622bae0e9b0ac3b422b5672a
🌴 **Code Settings Sync Version :** 3.2.0
🌴 **Standard or Insiders :** Insiders
🌴 **OSS or Portable :** Portable
🌴 **Operating System :** Windows 10, 1803 17134.345
🌴 **Occurs On:** Reset
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** bb76c23e3f687a22dc06aced7570918e

📰 **To Reproduce**
1. Open `Command Pallete`
1. Reset Extensions settings
1. See error

💪 **Expected behavior**
Settings should be cleared / resetted.

📺 **Console Error Log** 

```javascript
/S:/Scoop/apps/vscode-insiders/nightly-20181025/resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Error: ENOENT: no such file or directory, open 'C:\Users\Ash258\AppData\Roaming\user-data\User\syncLocalSettings.json' (at Function.<anonymous> (S:\Scoop\persist\vscode-insiders\data\extensions\shan.code-settings-sync-3.2.0\out\src\service\fileService.js:84:25))
t.log @ /S:/Scoop/apps/vscode-insiders/nightly-20181025/resources/app/out/vs/workbench/workbench.main.js:294
/S:/Scoop/apps/vscode-insiders/nightly-20181025/resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Error: ENOENT: no such file or directory, open 'C:\Users\Ash258\AppData\Roaming\user-data\User\sync.lock'
	at Object.fs.openSync (fs.js:646:18)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
	at Sync.<anonymous> (S:\Scoop\persist\vscode-insiders\data\extensions\shan.code-settings-sync-3.2.0\out\src\sync.js:511:37)
	at Generator.next (<anonymous>)
	at fulfilled (S:\Scoop\persist\vscode-insiders\data\extensions\shan.code-settings-sync-3.2.0\out\src\sync.js:4:58)
	at <anonymous> (at Function.LogException (S:\Scoop\persist\vscode-insiders\data\extensions\shan.code-settings-sync-3.2.0\out\src\commons.js:28:21))
t.log @ /S:/Scoop/apps/vscode-insiders/nightly-20181025/resources/app/out/vs/workbench/workbench.main.js:294
/S:/Scoop/apps/vscode-insiders/nightly-20181025/resources/app/out/vs/workbench/workbench.main.js:2427 Sync : Unable to clear settings. Error Logged on console. Please open an issue.
t.onDidNotificationChange @ /S:/Scoop/apps/vscode-insiders/nightly-20181025/resources/app/out/vs/workbench/workbench.main.js:2427
```

**Comment by shanalikhan** [comment]
It should be working now.
Let me know if there is a problem in reset the settings.
