### ISSUE TITLE
Command 'extension.downloadSettings' not found

### ISSUE THREAD

**Issue by CptFabulouso** [shanalikhan/code-settings-sync#716]
🐛 **Describe the bug**  
running the command throws error in the title. Seems like dependency problem, if anyone encouters same problem, "fix" is below.

🌴 **Visual Studio Code Version :** [ 1.29.1 ] 
🌴 **Code Settings Sync Version :** [ 3.2.2 ] 
🌴 **Standard or Insiders :** [ _here_ ] 
🌴 **OSS or Portable :** [ OSS ] 
🌴 **Operating System :** [ Windows 8.1 pro ] 
🌴 **Occurs On:** [ All of them ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [  ]

📰 **To Reproduce**
run the command

📺 **Console Error Log** 
```
 Activating extension `Shan.code-settings-sync` failed:  Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.


t.log @ /C:/Users/Pavel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:294
/C:/Users/Pavel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Here is the error stack:  Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.


	at makeError (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\execa\index.js:172:9)
	at Function.module.exports.sync (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\execa\index.js:341:15)
	at module.exports.release (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\windows-release\index.js:34:24)
	at module.exports (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\os-name\index.js:39:18)
	at getUserAgentNode (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\universal-user-agent\index.js:6:51)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\endpoint\lib\defaults.js:4:53)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\endpoint\lib\defaults.js:15:3)
	at Module.o._compile (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\endpoint\index.js:2:18)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\endpoint\index.js:6:3)
	at Module.o._compile (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\request\index.js:1:173)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\request\index.js:14:3)
	at Module.o._compile (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\constructor.js:3:18)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\constructor.js:21:3)
	at Module.o._compile (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\factory.js:3:17)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\factory.js:12:3)
	at Module.o._compile (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\core.js:1:172)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\core.js:5:3)
	at Module.o._compile (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\index.js:1:172)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\index.js:16:3)
	at Module.o._compile (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\out\src\service\githubService.js:11:19)
	at Object.<anonymous> (C:\Users\Pavel\.vscode\extensions\shan.code-settings-sync-3.2.2\out\src\service\githubService.js:151:3)
	at Module.o._compile (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (c:\Users\Pavel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
```

📺  **Quick and potentialy breaking fix, the best kind of fix**
After removing the part of code causing the error, it started working. 
Specifically removed all this from node_modules/windows_release/index.js, starting from line 33
```
if ((!release || release === os.release()) && ['6.1', '6.2', '6.3', '10.0'].includes(ver)) {
		const stdout = execa.sync('wmic', ['os', 'get', 'Caption']).stdout || ''; //this line causes the problem
		const year = (stdout.match(/2008|2012|2016/) || [])[0];
		if (year) {
			return `Server ${year}`;
		}
	}
```

I guess it isn't needed for my system and as a quick fix is enough for me.

**Comment by shanalikhan** [comment]
Try updating your node and npm.

**Comment by Local9** [comment]
Using the most recent version of NPM (6.5.0) and Node (11.4.0) this error was still showing, even removing and re-installing the extension showed the same error alone with a reinstall of Visual Studio Code.

I then looked into the developer terminal and found the wmic error was happening for me, to do a quick check this was missing from my PATH, along with some other stuff (don't know what messed with my PATH but its been a fun evening fixing it).

To quick fix this for most people on (Windows OS ofc) run ```sfc /scannow``` in an elevated command prompt window and let it run, go make a coffee or something, say to your project manager that your [compiling and do some jousting with a colleague](https://www.xkcd.com/303/).

After this, close command prompt, re-open it and check that ```wmic``` runs in it and if so, then all your problems are fixed! Now you can work, with a cold coffee because you was enjoying yourself too much with jousting and becoming the new leader of the break room.

Else, edit your in an elevated command prompt and add the following; ```setx path "%path%;c:\windows\system32\wbem"``` then restart code, issue should be fixed... IF and only IF this all fails, I ran VSC in admin and it then detected the sync settings update (note, I tried this earlier and it didn't work Windows 10, what a bane), when I closed and re-opened VSC the sync extension worked normally. What a journey.

Welcome to add this into the trouble shooting section, it might pop up a few times due to how windows PATH keeps being messed with.

**Comment by shanalikhan** [comment]
@Local9 thanks for providing detailed information.

https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting

It would be great if you can add the information in the Troubshooting section in wiki, public edit is allowed.
