### ISSUE TITLE
command 'extension.downloadSettings' not found, command 'extension.updateSettings' not found

### ISSUE THREAD

**Issue by guangshao** [shanalikhan/code-settings-sync#729]
🐛 **Describe the bug**  

🌴 **Visual Studio Code Version :** [ 1.29.1 ] 
🌴 **Code Settings Sync Version :** [ 3.2.2 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **OSS or Portable :** [ OSS ] 
🌴 **Operating System :** [ window 10 ] 
🌴 **Occurs On:** [Upload , Download , Help Configuring ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ ae8416e53f9eeb16a212186fc2e8eef0 ]

📰 **To Reproduce**

1. Install sync extension
2. Attempt to download
3. Receive error

💪 **Expected behavior**
Command to be called

📺 **Console Error Log** 
![qq 20181209224925](https://user-images.githubusercontent.com/12948503/49698875-e95c2900-fc04-11e8-95d2-f9d2fcd5008b.png)

[Extension Host] Here is the error stack:  Error: Command failed: wmic os get Caption
'wmic' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

	at makeError (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\execa\index.js:172:9)
	at Function.module.exports.sync (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\execa\index.js:341:15)
	at module.exports.release (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\windows-release\index.js:34:24)
	at module.exports (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\os-name\index.js:39:18)
	at getUserAgentNode (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\universal-user-agent\index.js:6:51)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\endpoint\lib\defaults.js:4:53)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\endpoint\lib\defaults.js:15:3)
	at Module.o._compile (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\endpoint\index.js:2:18)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\endpoint\index.js:6:3)
	at Module.o._compile (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\request\index.js:1:173)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\request\index.js:14:3)
	at Module.o._compile (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\constructor.js:3:18)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\constructor.js:21:3)
	at Module.o._compile (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\factory.js:3:17)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\factory.js:12:3)
	at Module.o._compile (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\core.js:1:172)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\lib\core.js:5:3)
	at Module.o._compile (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\index.js:1:172)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\node_modules\@octokit\rest\index.js:16:3)
	at Module.o._compile (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\out\src\service\githubService.js:11:19)
	at Object.<anonymous> (C:\Users\saosaoguang\.vscode\extensions\shan.code-settings-sync-3.2.2\out\src\service\githubService.js:151:3)
	at Module.o._compile (i:\soft\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.o._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.r._load (i:\soft\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)

📺  **Additional context**

**Comment by shanalikhan** [comment]
Delete extension folder. 
Install extension again and let me know if problem persists.
