### ISSUE TITLE
Unable to download settings in VS Code for macOS

### ISSUE THREAD

**Issue by hswami** [shanalikhan/code-settings-sync#781]
🐛 Download settings on VS Code for macOS shows errors in Developer Tools

🌴 **Visual Studio Code Version :** 1.31.1 1b8e8302e405050205e69b59abb3559592bb9e60 2019-02-12T02:10:22.500Z 
🌴 **Code Settings Sync Version :** 3.2.5
🌴 **Standard or Insiders :** Standard
🌴 **OSS or Portable :** OSS
🌴 **Operating System :** macOS Mojave 10.14.3 (18D109)
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** [secret]

📰 **To Reproduce**
1. Go to Command Pallette
2. Type 'sync'
3. Select 'Sync : Download Settings'
4. See the following errors in Developer Tools

💪 **Expected behavior**
I expected it to just work.

📺 **Console Error Log** 
console.ts:134 [Extension Host] Error: new Octokit({headers}) is deprecated. Use {userAgent, previews} instead. See https://github.com/octokit/rest.js#client-options
	at module.exports.e.exports (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:20:59007)
	at new module.exports.e.exports (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:14:33067)
	at new module.exports.t.GitHubService (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:14:31489)
	at /Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:32729
	at Generator.next (<anonymous>)
	at module.exports.n (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:27418)
	at new Promise (<anonymous>)
	at module.exports.n (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:27195)
	at /Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:32688
	at module.exports.t.Sync.<anonymous> (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:36667)
	at Generator.next (<anonymous>)
	at s (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:27251)
t.log @ console.ts:134
e.$logExtensionHostMessage @ mainThreadConsole.ts:39
t._doInvokeHandler @ rpcProtocol.ts:390
t._invokeHandler @ rpcProtocol.ts:375
t._receiveRequest @ rpcProtocol.ts:295
t._receiveOneMessage @ rpcProtocol.ts:225
(anonymous) @ rpcProtocol.ts:100
e.fire @ event.ts:567
s @ ipc.net.ts:295
(anonymous) @ ipc.net.ts:302
e.fire @ event.ts:567
a @ ipc.net.ts:103
_socketDataListener @ ipc.net.ts:132
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] Error: octokit.authenticate() is deprecated. Use "auth" constructor option instead.
	at module.exports.e.exports (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:20:64603)
	at new module.exports.t.GitHubService (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:14:31532)
	at /Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:32729
	at Generator.next (<anonymous>)
	at module.exports.n (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:27418)
	at new Promise (<anonymous>)
	at module.exports.n (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:27195)
	at /Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:32688
	at module.exports.t.Sync.<anonymous> (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:36667)
	at Generator.next (<anonymous>)
	at s (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:27251)
t.log @ console.ts:134
e.$logExtensionHostMessage @ mainThreadConsole.ts:39
t._doInvokeHandler @ rpcProtocol.ts:390
t._invokeHandler @ rpcProtocol.ts:375
t._receiveRequest @ rpcProtocol.ts:295
t._receiveOneMessage @ rpcProtocol.ts:225
(anonymous) @ rpcProtocol.ts:100
e.fire @ event.ts:567
s @ ipc.net.ts:295
(anonymous) @ ipc.net.ts:302
e.fire @ event.ts:567
a @ ipc.net.ts:103
_socketDataListener @ ipc.net.ts:132
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] HttpError: Not Found
	at module.exports.e.exports.i.fetch.then.n.text.then.r (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:1676)
	at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by LuisUrrutia** [comment]
related to #765 

> console.ts:134 [Extension Host] HttpError: Not Found
at module.exports.e.exports.i.fetch.then.n.text.then.r (/Users/himanshuswami/.vscode/extensions/shan.code-settings-sync-3.2.5/out/extension.js:7:1676)
at process._tickCallback (internal/process/next_tick.js:68:7)
