### ISSUE TITLE
Sync:Failed to connect to the network or connect to GitHub

### ISSUE THREAD

**Issue by imlijq** [shanalikhan/code-settings-sync#810]
Issue Type: <b>Bug</b>

Type shift+alt+d and use Settings Sync to download the configuration and prompt "Failed to connect to the network or connect to GitHub"

Console information：
```
workbench.main.js:sourcemap:235
 [Extension Host] Error: new Octokit({agent}) is deprecated. Use {request: {agent}} instead. See https://github.com/octokit/rest.js#client-options
	at module.exports.e.exports (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:20:59410)
	at new module.exports.e.exports (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:14:33018)
	at new module.exports.t.GitHubService (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:14:31500)
	at C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:32725
	at Generator.next (<anonymous>)
	at module.exports.n (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:27414)
	at new module.exports.e.exports (C:\Users\lijianqiang\.vscode-insiders\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:73069)
	at module.exports.n (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:27191)
	at C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:32684
	at module.exports.t.Sync.<anonymous> (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:36663)
	at Generator.next (<anonymous>)
	at s (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:27247)
	at o (C:\Users\lijianqiang\.vscode-insiders\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69130)
	at C:\Users\lijianqiang\.vscode-insiders\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69474 (at module.exports.e.exports (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:20:59405))
t.log @ workbench.main.js:sourcemap:235
$logExtensionHostMessage @ workbench.main.js:sourcemap:3178
_doInvokeHandler @ workbench.main.js:sourcemap:3306
_invokeHandler @ workbench.main.js:sourcemap:3305
_receiveRequest @ workbench.main.js:sourcemap:3304
_receiveOneMessage @ workbench.main.js:sourcemap:3303
_protocol.onMessage.e @ workbench.main.js:sourcemap:3301
fire @ workbench.main.js:sourcemap:75
a @ workbench.main.js:sourcemap:317
e @ workbench.main.js:sourcemap:317
fire @ workbench.main.js:sourcemap:75
_receiveMessage @ workbench.main.js:sourcemap:325
_socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:sourcemap:323
fire @ workbench.main.js:sourcemap:75
acceptChunk @ workbench.main.js:sourcemap:319
_register._socket.onData.e @ workbench.main.js:sourcemap:319
t @ workbench.main.js:sourcemap:328
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:sourcemap:235
 [Extension Host] HttpError: request to https://api.github.com/gists/883392718d8077ec9bfb63f17a6d4929 failed, reason: connect ETIMEDOUT 172.17.20.133:9080
	at module.exports.e.exports.then.then.catch.t (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:1963)
	at Promise.o [as __asl_wrapper] (C:\Users\lijianqiang\.vscode-insiders\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69130)
	at module.exports.n.__asl_wrapper (C:\Users\lijianqiang\.vscode-insiders\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69645)
	at C:\Users\lijianqiang\.vscode-insiders\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69474
	at process._tickCallback (internal/process/next_tick.js:68:7) (at Function.LogException (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:44292))
t.log @ workbench.main.js:sourcemap:235
$logExtensionHostMessage @ workbench.main.js:sourcemap:3178
_doInvokeHandler @ workbench.main.js:sourcemap:3306
_invokeHandler @ workbench.main.js:sourcemap:3305
_receiveRequest @ workbench.main.js:sourcemap:3304
_receiveOneMessage @ workbench.main.js:sourcemap:3303
_protocol.onMessage.e @ workbench.main.js:sourcemap:3301
fire @ workbench.main.js:sourcemap:75
a @ workbench.main.js:sourcemap:317
e @ workbench.main.js:sourcemap:317
fire @ workbench.main.js:sourcemap:75
_receiveMessage @ workbench.main.js:sourcemap:325
_socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:sourcemap:323
fire @ workbench.main.js:sourcemap:75
acceptChunk @ workbench.main.js:sourcemap:319
_register._socket.onData.e @ workbench.main.js:sourcemap:319
t @ workbench.main.js:sourcemap:328
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:sourcemap:235 
[Extension Host] HttpError: request to https://api.github.com/user failed, reason: connect ETIMEDOUT 172.17.20.133:9080
	at module.exports.e.exports.then.then.catch.t (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:1963)
	at Promise.o [as __asl_wrapper] (C:\Users\lijianqiang\.vscode-insiders\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69130)
	at module.exports.n.__asl_wrapper (C:\Users\lijianqiang\.vscode-insiders\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69645)
	at C:\Users\lijianqiang\.vscode-insiders\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69474
	at process._tickCallback (internal/process/next_tick.js:68:7) (at module.exports.t.GitHubService.constructor.github.users.getAuthenticated.then.catch.e (C:\Users\lijianqiang\.vscode-insiders\extensions\shan.code-settings-sync-3.2.7\out\extension.js:14:31716))
```

Extension version: 3.2.7
VS Code version: Code - Insiders 1.33.0-insider (a4989579d87b0bb82452c8166ea4089e50cea12e, 2019-03-26T23:22:39.444Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (7.85GB free)|
|Process Argv|D:\projects\workspace1.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by shanalikhan** [comment]
Can you try with latest version of Settings Sync ?

**Comment by imlijq** [comment]
I tried it, the latest version 3.2.8 does not have this problem, thank you
