### ISSUE TITLE
Upload setting failed

### ISSUE THREAD

**Issue by HugeKangroo** [shanalikhan/code-settings-sync#880]
🐛 **Describe the bug**  
when upload vscode setting, it gets "Internet Not Connected or Unable to Connect to GitHub. Exception Logged in Console" message.

🌴 **Visual Studio Code Version :1.33.1
🌴 **Code Settings Sync Version :3.2.9
🌴 **Standard or Insiders :standard
🌴 **Portable or Installed :Installed
🌴 **OSS or Official Build :N/A
🌴 **Operating System :ubuntu 16.04
🌴 **Occurs On:Upload
🌴 **Proxy Enabled:not sure
🌴 **Gist Id:N/A

📰 **To Reproduce**
1. Sync : Reset Extension Settings
2. Sync : Update / Upload Settings
3. [I enter my personal access token]
4. Get error on status line: Internet Not Connected or Unable to Connect to GitHub. Exception Logged in Console

💪 **Expected behavior**
upload setting to github gist

📺 **Console Error Log** 
console.ts:134 [Extension Host] HttpError: request to https://api.github.com/user failed, reason: Client network socket disconnected before secure TLS connection was established at module.exports.e.exports.then.then.catch.t (/home/joey/.vscode/extensions/shan.code-settings-sync-3.2.9/out/extension.js:176:50468) at process._tickCallback (internal/process/next_tick.js:68:7)
console.ts:134 [Extension Host] HttpError: request to https://api.github.com/gists failed, reason: Client network socket disconnected before secure TLS connection was established at module.exports.e.exports.then.then.catch.t (/home/joey/.vscode/extensions/shan.code-settings-sync-3.2.9/out/extension.js:176:50468)	at process._tickCallback (internal/process/next_tick.js:68:7)

📺  **Additional context**
Almost the same problem which mentioned in this [issue](https://github.com/shanalikhan/code-settings-sync/issues/802) But the fix is not working for me

**Comment by SeanRParker** [comment]
I'm hitting this same issue. Installing older versions of the extension and using `win-ca` just creates a "not connected to Internet or Github" message.

**Comment by mountainguan** [comment]
I get the same error

**Comment by andybeeching** [comment]
I'm also experiencing this problem, except my error code is a little different. Setup as follows:

🐛 Describe the bug
when upload vscode setting, it gets "Internet Not Connected or Unable to Connect to GitHub. Exception Logged in Console" message.

🌴 **Visual Studio Code Version :1.34
🌴 **Code Settings Sync Version :3.2.9
🌴 **Standard or Insiders :Standard
🌴 **Portable or Installed :Installed
🌴 **OSS or Official Build :N/A
🌴 **Operating System OSX 10.13.6 (High Sierra)
🌴 **Occurs On:Upload
🌴 **Proxy Enabled:Not sure, but think not.
🌴 **Gist Id:N/A

📰 To Reproduce
Steps to reproduce the behavior:

Sync : Reset Extension Settings
Sync : Update / Upload Settings
[I enter my personal access token]
Get error on status line: Internet Not Connected or Unable to Connect to GitHub. Exception Logged in Console
💪 Expected behavior
upload setting to github gist

📺 Console Error Log
HttpError: request to https://api.github.com/gists/[MT_TOKEN] failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at module.exports.e.exports.then.then.catch.t (/Users/fred/.vscode/extensions/shan.code-settings-sync-3.2.9/out/extension.js:176:50468)
	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238

📺 Additional context

I have tried killing all other chrome processes, and disabled other extensions in case they were interfering to no avail. Given the local nature of the issue I feel I'm overlooking something obvious!

**Comment by andybeeching** [comment]
Alright, I figured out my issue - seems as I had dowloaded an old settings.json file (1.5 years old!), it included some proxy settings from a previous environment I had forgotten about.

Removing these proxy values allowed the extension to successfully communicate with the Github API and upload my changes. Leaving this here for posterity in case someone else runs into the same issue.

**Comment by shanalikhan** [comment]
This is related to proxy, you guys either have proxy setup or using insecure certificates for github.
If you are using code in Windows in WSL, see this https://github.com/shanalikhan/code-settings-sync/issues/903

**Comment by andreypudov** [comment]
I have a similar issue with uploading settings on Mac (the same, directly and via proxy):

[Extension Host] Sync : Connected with user : '<id>'
[Extension Host] HttpError: Not Found
	at module.exports.e.exports.then.n.text.then.r (~/.vscode/extensions/shan.code-settings-sync-3.2.9/out/extension.js:176:50169)
	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ /Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238

**Comment by shanalikhan** [comment]
@andreypudov 

>[Extension Host] Sync : Connected with user : ''
[Extension Host] HttpError: Not Found

Checkout the [troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) here.

**Comment by andreypudov** [comment]
> @andreypudov
> 
> > [Extension Host] Sync : Connected with user : ''
> > [Extension Host] HttpError: Not Found
> 
> Checkout the [troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) here.

Thank you so much! It works!

**Comment by shanalikhan** [comment]
Check the [solution for unable to connect to github](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting#fix-sync-internet-not-connected-or-unable-to-connect-to-github-exception-logged-in-console-windows-only) here.

Let me know if it helped, i will close this ticket.

**Comment by sarahgerweck** [comment]
I'm getting this consistently recently on my Mac, so I don't think it's the Windows issue. Here's the error in the console:

>    `[Extension Host] HttpError: request to https://api.github.com/user failed, reason: certificate has expired	at module.exports.then.then.catch.t (/Users/sarah/.vscode/extensions/shan.code-settings-sync-3.4.1/out/extension.js:761:1113)	at process._tickCallback (internal/process/next_tick.js:68:7)`
>     `t.log @ console.ts:137`

I got it to go away once by disabling and reenabling Settings Sync, but it came back the next day. It's driving me nuts because I don't like being without settings sync.
