### ISSUE TITLE
Sync appears to not actually be downloading and applying extensions

### ISSUE THREAD

**Issue by willstocks-tech** [shanalikhan/code-settings-sync#912]
Hi guys,

I have a fresh install of VS Code on Win 10. The first (and only!) thing I did was install Settings Sync and configure that to download my themes, extensions and settings.

My `settings.json` has been imported correctly and I can see that my 15 extensions (in theory) go through the process of being downloaded/installed, but they don't _actually_ get installed. When I press "Apply settings & extensions" once the download/install is done, VS Code reloads but nothing changes, it's just a plain VS Code installation with my custom `settings.json` and no extensions/themes/icons.

This is very strange, because I set up my MacBook over the weekend and had no issues with the download process then, so assumed there would be no issue here?

Please let me know what info you need me to obtain and I will supply ASAP 😄

**Comment by willstocks-tech** [comment]
I see this in `\AppData\Roaming\Code\logs\20190618T123049\exthost1\output_logging_20190618T124508`

```
COMMAND LINE EXTENSION DOWNLOAD SUMMARY
--------------------
TOTAL EXTENSIONS : 15


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension formulahendry.auto-close-tag
Installing extensions...


EXTENSION : 1 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension formulahendry.auto-rename-tag
Installing extensions...


EXTENSION : 2 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension CoenraadS.bracket-pair-colorizer-2
Installing extensions...


EXTENSION : 3 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension dsznajder.es7-react-js-snippets
Installing extensions...


EXTENSION : 4 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension eamodio.gitlens
Installing extensions...


EXTENSION : 5 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension gencer.html-slim-scss-css-class-completion
Installing extensions...


EXTENSION : 6 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension abusaidm.html-snippets
Installing extensions...


EXTENSION : 7 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension PKief.material-icon-theme
Installing extensions...


EXTENSION : 8 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension christian-kohler.path-intellisense
Installing extensions...


EXTENSION : 9 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension pnp.polacode
Installing extensions...


EXTENSION : 10 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension esbenp.prettier-vscode
Installing extensions...


EXTENSION : 11 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension WallabyJs.quokka-vscode
Installing extensions...


EXTENSION : 12 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension Equinusocio.vsc-material-theme
Installing extensions...


EXTENSION : 13 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension pranaygp.vscode-css-peek
Installing extensions...


EXTENSION : 14 / 15 INSTALLED.


"C:\Users\Will.Stocks2\AppData\Local\Programs\Microsoft VS Code\bin/code" --install-extension wix.vscode-import-cost
Installing extensions...


EXTENSION : 15 / 15 INSTALLED.


CODE SETTINGS SYNC DOWNLOAD SUMMARY
Version: 3.2.9
--------------------
GitHub Token: c6733225aaee3987b143472608e23be48fb85015
GitHub Gist: 4eaba17f3efbf07257c0503521aa1fab
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Downloaded:
  extensions.json > extensions.json
  keybindings.json > keybindings.json
  settings.json > settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  auto-close-tag v0.5.6
  auto-rename-tag v0.1.0
  bracket-pair-colorizer-2 v0.0.28
  es7-react-js-snippets v2.3.0
  gitlens v9.8.2
  html-slim-scss-css-class-completion v1.5.17
  html-snippets v0.2.1
  material-icon-theme v3.8.0
  path-intellisense v1.4.2
  polacode v0.3.2
  prettier-vscode v1.9.0
  quokka-vscode v1.0.227
  vsc-material-theme v2.9.0
  vscode-css-peek v2.2.0
  vscode-import-cost v2.12.0
--------------------
Done.
```

`\AppData\Roaming\Code\User\` also has 
- `keybindings.json`
- `settings.json`
- `syncLocalSettings.json`

But no `extensions.json`?

**Comment by willstocks-tech** [comment]
I've just checked my gist and have noticed that when I last tried to download, for some reason my `extensions.json` was wiped, apart from settings-sync. I've just rebuilt my `extensions.json` and I'm now trying to force a re-download.

**Comment by willstocks-tech** [comment]
`extension.json` rebuilt and still my extensions don't actually appear to be downloading and installing, despite the console output tab showing that they are.

`extensions.json` for reference:

```json
[
  {
    "metadata": {
      "id": "d3836729-9cc1-42c1-b2af-d50071f57d29",
      "publisherId": "formulahendry.auto-close-tag",
      "publisherDisplayName": "formulahendry"
    },
    "name": "auto-close-tag",
    "publisher": "formulahendry",
    "version": "0.5.6"
  },
  {
    "metadata": {
      "id": "6e440e71-8ed9-4f25-bb78-4b13096b8a03",
      "publisherId": "formulahendry.auto-rename-tag",
      "publisherDisplayName": "formulahendry"
    },
    "name": "auto-rename-tag",
    "publisher": "formulahendry",
    "version": "0.1.0"
  },
  {
    "metadata": {
      "id": "5a6e2b21-1d61-4acd-b31b-907f9c23f18a",
      "publisherId": "CoenraadS.bracket-pair-colorizer-2",
      "publisherDisplayName": "CoenraadS"
    },
    "name": "bracket-pair-colorizer-2",
    "publisher": "CoenraadS",
    "version": "0.0.28"
  },
  {
    "metadata": {
      "id": "e337c67b-55c2-4fef-8949-eb260e7fb7fd",
      "publisherId": "Shan.code-settings-sync",
      "publisherDisplayName": "Shan"
    },
    "name": "code-settings-sync",
    "publisher": "Shan",
    "version": "3.2.9"
  },
  {
    "metadata": {
      "id": "19804510-b475-4dae-b0f7-6ca08fd1af0c",
      "publisherId": "dsznajder.es7-react-js-snippets",
      "publisherDisplayName": "dsznajder"
    },
    "name": "es7-react-js-snippets",
    "publisher": "dsznajder",
    "version": "2.3.0"
  },
  {
    "metadata": {
      "id": "4de763bd-505d-4978-9575-2b7696ecf94e",
      "publisherId": "eamodio.gitlens",
      "publisherDisplayName": "eamodio"
    },
    "name": "gitlens",
    "publisher": "eamodio",
    "version": "9.8.1"
  },
  {
    "metadata": {
      "id": "07734f09-9218-443a-abfa-a9a823d2c25a",
      "publisherId": "gencer.html-slim-scss-css-class-completion",
      "publisherDisplayName": "gencer"
    },
    "name": "html-slim-scss-css-class-completion",
    "publisher": "gencer",
    "version": "1.5.14"
  },
  {
    "metadata": {
      "id": "be992f3f-9f22-4b66-a1d2-ecad04c28a28",
      "publisherId": "abusaidm.html-snippets",
      "publisherDisplayName": "abusaidm"
    },
    "name": "html-snippets",
    "publisher": "abusaidm",
    "version": "0.2.1"
  },
  {
    "metadata": {
      "id": "5db78037-f674-459f-a236-db622c427c5b",
      "publisherId": "PKief.material-icon-theme",
      "publisherDisplayName": "PKief"
    },
    "name": "material-icon-theme",
    "publisher": "PKief",
    "version": "3.8.0"
  },
  {
    "metadata": {
      "id": "0d1241e3-fa60-4f24-8f2a-6d7085677c48",
      "publisherId": "ionutvmi.path-autocomplete",
      "publisherDisplayName": "ionutvmi"
    },
    "name": "path-autocomplete",
    "publisher": "ionutvmi",
    "version": "1.13.3"
  },
  {
    "metadata": {
      "id": "a41c1549-4053-44d4-bf30-60fc809b4a86",
      "publisherId": "christian-kohler.path-intellisense",
      "publisherDisplayName": "christian-kohler"
    },
    "name": "path-intellisense",
    "publisher": "christian-kohler",
    "version": "1.4.2"
  },
  {
    "metadata": {
      "id": "d80b9a94-f4a6-4e39-bc42-62212e365682",
      "publisherId": "pnp.polacode",
      "publisherDisplayName": "pnp"
    },
    "name": "polacode",
    "publisher": "pnp",
    "version": "0.3.2"
  },
  {
    "metadata": {
      "id": "96fa4707-6983-4489-b7c5-d5ffdfdcce90",
      "publisherId": "esbenp.prettier-vscode",
      "publisherDisplayName": "esbenp"
    },
    "name": "prettier-vscode",
    "publisher": "esbenp",
    "version": "1.9.0"
  },
  {
    "metadata": {
      "id": "aae0701b-111f-49c1-9000-abd37a442f28",
      "publisherId": "WallabyJs.quokka-vscode",
      "publisherDisplayName": "WallabyJs"
    },
    "name": "quokka-vscode",
    "publisher": "WallabyJs",
    "version": "1.0.225"
  },
  {
    "metadata": {
      "id": "dffaf5a1-2219-434b-9d87-cb586fd59260",
      "publisherId": "Equinusocio.vsc-material-theme",
      "publisherDisplayName": "Equinusocio"
    },
    "name": "vsc-material-theme",
    "publisher": "Equinusocio",
    "version": "2.9.0"
  },
  {
    "metadata": {
      "id": "0b8f8d63-11a2-4194-969c-ca7488b3413a",
      "publisherId": "pranaygp.vscode-css-peek",
      "publisherDisplayName": "pranaygp"
    },
    "name": "vscode-css-peek",
    "publisher": "pranaygp",
    "version": "2.2.0"
  },
  {
    "metadata": {
      "id": "c46b0018-f317-4b6c-a785-d2039b27338f",
      "publisherId": "wix.vscode-import-cost",
      "publisherDisplayName": "wix"
    },
    "name": "vscode-import-cost",
    "publisher": "wix",
    "version": "2.12.0"
  }
] 
```

**Comment by arnohovhannisyan** [comment]
@willstocks-tech 

> VS Code reloads but nothing changes, it's just a plain VS Code installation with my custom settings.json and no extensions/themes/icons.

Can you try out this build? https://cdn.discordapp.com/attachments/549007146868539408/585286719155208193/code-settings-sync-3.2.9.vsix

> But no extensions.json?

The `extensions.json` file will never appear on your local machine. It is created on the fly and uploaded to the gist, and the extension uses this file to install the extensions listed in it. It is never actually written to the disk.

**Comment by willstocks-tech** [comment]
Hi @arnohovhannisyan 

Have just installed that VSIX and an error was logged (to devtools) when I tried to (force) download settings

```
TypeError: addedExtensions.forEach is not a function
	at Commons.module.exports../src/commons.ts.Commons.ShowSummaryOutput (C:\Users\willstocks\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:52004:29)
	at C:\Users\willstocks\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:54496:53
	at step (C:\Users\willstocks\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:53937:23)
	at Object.module.exports../src/sync.ts.f [as next] (C:\Users\willstocks\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:53918:53)
	at fulfilled (C:\Users\willstocks\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:53909:58)
```

**Comment by arnohovhannisyan** [comment]
@willstocks-tech Here is a more up-to-date build that should hopefully fix that: https://cdn.discordapp.com/attachments/549007146868539408/590818228452851713/code-settings-sync-3.2.9.vsix

**Comment by willstocks-tech** [comment]
Thanks @arnohovhannisyan 

Installed and now I'm seeing:

```
Sync: Result content is not a valid JSON. Unexpected end of JSON input
t.log @ workbench.main.js:238
```

and

```
[Extension Host] TypeError: i.forEach is not a function
	at e.module.exports.e.ShowSummaryOutput (C:\Users\willstocks\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:162:110209)
	at C:\Users\willstocks\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:162:87537
	at C:\Users\willstocks\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:162:76352
	at Object.module.exports.i [as next] (C:\Users\willstocks\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:162:76457)
	at s (C:\Users\willstocks\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:162:75203)
```

**Comment by arnohovhannisyan** [comment]
@willstocks-tech This version has source maps so we can know exactly what's causing the issue: https://cdn.discordapp.com/attachments/549007146868539408/590821294811906069/code-settings-sync-3.2.9.vsix. It should also fix the second error.

**Comment by willstocks-tech** [comment]
@arnohovhannisyan Installed and extensions appear to be installing!!

**Comment by willstocks-tech** [comment]
@arnohovhannisyan - I can confirm, my extensions are all now installed and configured and themes etc. applied! 😁 

Thank you for your assistance!

**Comment by cpratlong** [comment]
FYI i had same issue and i confirm the below version resolved it for me as well

https://cdn.discordapp.com/attachments/549007146868539408/590821294811906069/code-settings-sync-3.2.9.vsix

**Comment by shanalikhan** [comment]
I have released new version of Settings Sync v3.3.0 fixing this issue. Im closing this ticket let me know if u guys run into some problem

**Comment by brendanmatkin** [comment]
I'm having this same problem but with Settings Sync v3.4.1

**Comment by brendanmatkin** [comment]
More details: (it used to work)
It's being uploaded from my Windows PC. I can see the gist is updated and all contains valid JSON. Am downloading on my Mac (VSCode 1.36.1). 

"Result content is not a valid JSON" only appears in console when I enable Force Download, but the status bar says "Sync: you already have the latest.."

**Comment by brendanmatkin** [comment]
SORRY ignore my comments - somehow the gist ID changed between now and when I used it last, so each computer started writing to it's own gist. Maybe that is another bug, maybe I did something. If I figure out how it happened I'll post or make an issue. Sorry 'bout that!
